/**
 * generated by Xtext 2.27.0
 */
package org.omnia.metamodel.metamodel.impl;

import java.util.Collection;

import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import org.eclipse.emf.ecore.util.EObjectContainmentEList;
import org.eclipse.emf.ecore.util.InternalEList;

import org.omnia.metamodel.metamodel.Agent;
import org.omnia.metamodel.metamodel.App;
import org.omnia.metamodel.metamodel.ApplicationBehaviour;
import org.omnia.metamodel.metamodel.ApplicationMenu;
import org.omnia.metamodel.metamodel.AuthorizationPolicy;
import org.omnia.metamodel.metamodel.AuthorizationRole;
import org.omnia.metamodel.metamodel.Commitement;
import org.omnia.metamodel.metamodel.Dashboard;
import org.omnia.metamodel.metamodel.DataSource;
import org.omnia.metamodel.metamodel.Document;
import org.omnia.metamodel.metamodel.Enumeration;
import org.omnia.metamodel.metamodel.Event;
import org.omnia.metamodel.metamodel.Form;
import org.omnia.metamodel.metamodel.GenericEntity;
import org.omnia.metamodel.metamodel.Language;
import org.omnia.metamodel.metamodel.List;
import org.omnia.metamodel.metamodel.MetamodelPackage;
import org.omnia.metamodel.metamodel.Query;
import org.omnia.metamodel.metamodel.Resource;
import org.omnia.metamodel.metamodel.Selector;
import org.omnia.metamodel.metamodel.Serie;
import org.omnia.metamodel.metamodel.StateMachine;
import org.omnia.metamodel.metamodel.TextTemplate;
import org.omnia.metamodel.metamodel.Theme;
import org.omnia.metamodel.metamodel.WebComponent;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>App</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link org.omnia.metamodel.metamodel.impl.AppImpl#getAgents <em>Agents</em>}</li>
 *   <li>{@link org.omnia.metamodel.metamodel.impl.AppImpl#getApplicationBehaviours <em>Application Behaviours</em>}</li>
 *   <li>{@link org.omnia.metamodel.metamodel.impl.AppImpl#getCommitements <em>Commitements</em>}</li>
 *   <li>{@link org.omnia.metamodel.metamodel.impl.AppImpl#getDashboards <em>Dashboards</em>}</li>
 *   <li>{@link org.omnia.metamodel.metamodel.impl.AppImpl#getDatasources <em>Datasources</em>}</li>
 *   <li>{@link org.omnia.metamodel.metamodel.impl.AppImpl#getDocuments <em>Documents</em>}</li>
 *   <li>{@link org.omnia.metamodel.metamodel.impl.AppImpl#getEnumerations <em>Enumerations</em>}</li>
 *   <li>{@link org.omnia.metamodel.metamodel.impl.AppImpl#getForms <em>Forms</em>}</li>
 *   <li>{@link org.omnia.metamodel.metamodel.impl.AppImpl#getGenericEntities <em>Generic Entities</em>}</li>
 *   <li>{@link org.omnia.metamodel.metamodel.impl.AppImpl#getLists <em>Lists</em>}</li>
 *   <li>{@link org.omnia.metamodel.metamodel.impl.AppImpl#getQueries <em>Queries</em>}</li>
 *   <li>{@link org.omnia.metamodel.metamodel.impl.AppImpl#getResources <em>Resources</em>}</li>
 *   <li>{@link org.omnia.metamodel.metamodel.impl.AppImpl#getSelectors <em>Selectors</em>}</li>
 *   <li>{@link org.omnia.metamodel.metamodel.impl.AppImpl#getSeries <em>Series</em>}</li>
 *   <li>{@link org.omnia.metamodel.metamodel.impl.AppImpl#getStateMachines <em>State Machines</em>}</li>
 *   <li>{@link org.omnia.metamodel.metamodel.impl.AppImpl#getEvents <em>Events</em>}</li>
 *   <li>{@link org.omnia.metamodel.metamodel.impl.AppImpl#getApplicationMenus <em>Application Menus</em>}</li>
 *   <li>{@link org.omnia.metamodel.metamodel.impl.AppImpl#getLanguages <em>Languages</em>}</li>
 *   <li>{@link org.omnia.metamodel.metamodel.impl.AppImpl#getWebComponents <em>Web Components</em>}</li>
 *   <li>{@link org.omnia.metamodel.metamodel.impl.AppImpl#getTextTemplates <em>Text Templates</em>}</li>
 *   <li>{@link org.omnia.metamodel.metamodel.impl.AppImpl#getThemes <em>Themes</em>}</li>
 *   <li>{@link org.omnia.metamodel.metamodel.impl.AppImpl#getAuthorizationPolicies <em>Authorization Policies</em>}</li>
 *   <li>{@link org.omnia.metamodel.metamodel.impl.AppImpl#getAuthorizationRoles <em>Authorization Roles</em>}</li>
 * </ul>
 *
 * @generated
 */
public class AppImpl extends MinimalEObjectImpl.Container implements App
{
  /**
   * The cached value of the '{@link #getAgents() <em>Agents</em>}' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getAgents()
   * @generated
   * @ordered
   */
  protected EList<Agent> agents;

  /**
   * The cached value of the '{@link #getApplicationBehaviours() <em>Application Behaviours</em>}' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getApplicationBehaviours()
   * @generated
   * @ordered
   */
  protected EList<ApplicationBehaviour> applicationBehaviours;

  /**
   * The cached value of the '{@link #getCommitements() <em>Commitements</em>}' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getCommitements()
   * @generated
   * @ordered
   */
  protected EList<Commitement> commitements;

  /**
   * The cached value of the '{@link #getDashboards() <em>Dashboards</em>}' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getDashboards()
   * @generated
   * @ordered
   */
  protected EList<Dashboard> dashboards;

  /**
   * The cached value of the '{@link #getDatasources() <em>Datasources</em>}' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getDatasources()
   * @generated
   * @ordered
   */
  protected EList<DataSource> datasources;

  /**
   * The cached value of the '{@link #getDocuments() <em>Documents</em>}' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getDocuments()
   * @generated
   * @ordered
   */
  protected EList<Document> documents;

  /**
   * The cached value of the '{@link #getEnumerations() <em>Enumerations</em>}' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getEnumerations()
   * @generated
   * @ordered
   */
  protected EList<Enumeration> enumerations;

  /**
   * The cached value of the '{@link #getForms() <em>Forms</em>}' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getForms()
   * @generated
   * @ordered
   */
  protected EList<Form> forms;

  /**
   * The cached value of the '{@link #getGenericEntities() <em>Generic Entities</em>}' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getGenericEntities()
   * @generated
   * @ordered
   */
  protected EList<GenericEntity> genericEntities;

  /**
   * The cached value of the '{@link #getLists() <em>Lists</em>}' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getLists()
   * @generated
   * @ordered
   */
  protected EList<List> lists;

  /**
   * The cached value of the '{@link #getQueries() <em>Queries</em>}' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getQueries()
   * @generated
   * @ordered
   */
  protected EList<Query> queries;

  /**
   * The cached value of the '{@link #getResources() <em>Resources</em>}' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getResources()
   * @generated
   * @ordered
   */
  protected EList<Resource> resources;

  /**
   * The cached value of the '{@link #getSelectors() <em>Selectors</em>}' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getSelectors()
   * @generated
   * @ordered
   */
  protected EList<Selector> selectors;

  /**
   * The cached value of the '{@link #getSeries() <em>Series</em>}' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getSeries()
   * @generated
   * @ordered
   */
  protected EList<Serie> series;

  /**
   * The cached value of the '{@link #getStateMachines() <em>State Machines</em>}' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getStateMachines()
   * @generated
   * @ordered
   */
  protected EList<StateMachine> stateMachines;

  /**
   * The cached value of the '{@link #getEvents() <em>Events</em>}' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getEvents()
   * @generated
   * @ordered
   */
  protected EList<Event> events;

  /**
   * The cached value of the '{@link #getApplicationMenus() <em>Application Menus</em>}' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getApplicationMenus()
   * @generated
   * @ordered
   */
  protected EList<ApplicationMenu> applicationMenus;

  /**
   * The cached value of the '{@link #getLanguages() <em>Languages</em>}' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getLanguages()
   * @generated
   * @ordered
   */
  protected EList<Language> languages;

  /**
   * The cached value of the '{@link #getWebComponents() <em>Web Components</em>}' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getWebComponents()
   * @generated
   * @ordered
   */
  protected EList<WebComponent> webComponents;

  /**
   * The cached value of the '{@link #getTextTemplates() <em>Text Templates</em>}' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getTextTemplates()
   * @generated
   * @ordered
   */
  protected EList<TextTemplate> textTemplates;

  /**
   * The cached value of the '{@link #getThemes() <em>Themes</em>}' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getThemes()
   * @generated
   * @ordered
   */
  protected EList<Theme> themes;

  /**
   * The cached value of the '{@link #getAuthorizationPolicies() <em>Authorization Policies</em>}' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getAuthorizationPolicies()
   * @generated
   * @ordered
   */
  protected EList<AuthorizationPolicy> authorizationPolicies;

  /**
   * The cached value of the '{@link #getAuthorizationRoles() <em>Authorization Roles</em>}' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getAuthorizationRoles()
   * @generated
   * @ordered
   */
  protected EList<AuthorizationRole> authorizationRoles;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected AppImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return MetamodelPackage.Literals.APP;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EList<Agent> getAgents()
  {
    if (agents == null)
    {
      agents = new EObjectContainmentEList<Agent>(Agent.class, this, MetamodelPackage.APP__AGENTS);
    }
    return agents;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EList<ApplicationBehaviour> getApplicationBehaviours()
  {
    if (applicationBehaviours == null)
    {
      applicationBehaviours = new EObjectContainmentEList<ApplicationBehaviour>(ApplicationBehaviour.class, this, MetamodelPackage.APP__APPLICATION_BEHAVIOURS);
    }
    return applicationBehaviours;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EList<Commitement> getCommitements()
  {
    if (commitements == null)
    {
      commitements = new EObjectContainmentEList<Commitement>(Commitement.class, this, MetamodelPackage.APP__COMMITEMENTS);
    }
    return commitements;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EList<Dashboard> getDashboards()
  {
    if (dashboards == null)
    {
      dashboards = new EObjectContainmentEList<Dashboard>(Dashboard.class, this, MetamodelPackage.APP__DASHBOARDS);
    }
    return dashboards;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EList<DataSource> getDatasources()
  {
    if (datasources == null)
    {
      datasources = new EObjectContainmentEList<DataSource>(DataSource.class, this, MetamodelPackage.APP__DATASOURCES);
    }
    return datasources;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EList<Document> getDocuments()
  {
    if (documents == null)
    {
      documents = new EObjectContainmentEList<Document>(Document.class, this, MetamodelPackage.APP__DOCUMENTS);
    }
    return documents;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EList<Enumeration> getEnumerations()
  {
    if (enumerations == null)
    {
      enumerations = new EObjectContainmentEList<Enumeration>(Enumeration.class, this, MetamodelPackage.APP__ENUMERATIONS);
    }
    return enumerations;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EList<Form> getForms()
  {
    if (forms == null)
    {
      forms = new EObjectContainmentEList<Form>(Form.class, this, MetamodelPackage.APP__FORMS);
    }
    return forms;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EList<GenericEntity> getGenericEntities()
  {
    if (genericEntities == null)
    {
      genericEntities = new EObjectContainmentEList<GenericEntity>(GenericEntity.class, this, MetamodelPackage.APP__GENERIC_ENTITIES);
    }
    return genericEntities;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EList<List> getLists()
  {
    if (lists == null)
    {
      lists = new EObjectContainmentEList<List>(List.class, this, MetamodelPackage.APP__LISTS);
    }
    return lists;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EList<Query> getQueries()
  {
    if (queries == null)
    {
      queries = new EObjectContainmentEList<Query>(Query.class, this, MetamodelPackage.APP__QUERIES);
    }
    return queries;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EList<Resource> getResources()
  {
    if (resources == null)
    {
      resources = new EObjectContainmentEList<Resource>(Resource.class, this, MetamodelPackage.APP__RESOURCES);
    }
    return resources;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EList<Selector> getSelectors()
  {
    if (selectors == null)
    {
      selectors = new EObjectContainmentEList<Selector>(Selector.class, this, MetamodelPackage.APP__SELECTORS);
    }
    return selectors;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EList<Serie> getSeries()
  {
    if (series == null)
    {
      series = new EObjectContainmentEList<Serie>(Serie.class, this, MetamodelPackage.APP__SERIES);
    }
    return series;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EList<StateMachine> getStateMachines()
  {
    if (stateMachines == null)
    {
      stateMachines = new EObjectContainmentEList<StateMachine>(StateMachine.class, this, MetamodelPackage.APP__STATE_MACHINES);
    }
    return stateMachines;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EList<Event> getEvents()
  {
    if (events == null)
    {
      events = new EObjectContainmentEList<Event>(Event.class, this, MetamodelPackage.APP__EVENTS);
    }
    return events;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EList<ApplicationMenu> getApplicationMenus()
  {
    if (applicationMenus == null)
    {
      applicationMenus = new EObjectContainmentEList<ApplicationMenu>(ApplicationMenu.class, this, MetamodelPackage.APP__APPLICATION_MENUS);
    }
    return applicationMenus;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EList<Language> getLanguages()
  {
    if (languages == null)
    {
      languages = new EObjectContainmentEList<Language>(Language.class, this, MetamodelPackage.APP__LANGUAGES);
    }
    return languages;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EList<WebComponent> getWebComponents()
  {
    if (webComponents == null)
    {
      webComponents = new EObjectContainmentEList<WebComponent>(WebComponent.class, this, MetamodelPackage.APP__WEB_COMPONENTS);
    }
    return webComponents;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EList<TextTemplate> getTextTemplates()
  {
    if (textTemplates == null)
    {
      textTemplates = new EObjectContainmentEList<TextTemplate>(TextTemplate.class, this, MetamodelPackage.APP__TEXT_TEMPLATES);
    }
    return textTemplates;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EList<Theme> getThemes()
  {
    if (themes == null)
    {
      themes = new EObjectContainmentEList<Theme>(Theme.class, this, MetamodelPackage.APP__THEMES);
    }
    return themes;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EList<AuthorizationPolicy> getAuthorizationPolicies()
  {
    if (authorizationPolicies == null)
    {
      authorizationPolicies = new EObjectContainmentEList<AuthorizationPolicy>(AuthorizationPolicy.class, this, MetamodelPackage.APP__AUTHORIZATION_POLICIES);
    }
    return authorizationPolicies;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EList<AuthorizationRole> getAuthorizationRoles()
  {
    if (authorizationRoles == null)
    {
      authorizationRoles = new EObjectContainmentEList<AuthorizationRole>(AuthorizationRole.class, this, MetamodelPackage.APP__AUTHORIZATION_ROLES);
    }
    return authorizationRoles;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case MetamodelPackage.APP__AGENTS:
        return ((InternalEList<?>)getAgents()).basicRemove(otherEnd, msgs);
      case MetamodelPackage.APP__APPLICATION_BEHAVIOURS:
        return ((InternalEList<?>)getApplicationBehaviours()).basicRemove(otherEnd, msgs);
      case MetamodelPackage.APP__COMMITEMENTS:
        return ((InternalEList<?>)getCommitements()).basicRemove(otherEnd, msgs);
      case MetamodelPackage.APP__DASHBOARDS:
        return ((InternalEList<?>)getDashboards()).basicRemove(otherEnd, msgs);
      case MetamodelPackage.APP__DATASOURCES:
        return ((InternalEList<?>)getDatasources()).basicRemove(otherEnd, msgs);
      case MetamodelPackage.APP__DOCUMENTS:
        return ((InternalEList<?>)getDocuments()).basicRemove(otherEnd, msgs);
      case MetamodelPackage.APP__ENUMERATIONS:
        return ((InternalEList<?>)getEnumerations()).basicRemove(otherEnd, msgs);
      case MetamodelPackage.APP__FORMS:
        return ((InternalEList<?>)getForms()).basicRemove(otherEnd, msgs);
      case MetamodelPackage.APP__GENERIC_ENTITIES:
        return ((InternalEList<?>)getGenericEntities()).basicRemove(otherEnd, msgs);
      case MetamodelPackage.APP__LISTS:
        return ((InternalEList<?>)getLists()).basicRemove(otherEnd, msgs);
      case MetamodelPackage.APP__QUERIES:
        return ((InternalEList<?>)getQueries()).basicRemove(otherEnd, msgs);
      case MetamodelPackage.APP__RESOURCES:
        return ((InternalEList<?>)getResources()).basicRemove(otherEnd, msgs);
      case MetamodelPackage.APP__SELECTORS:
        return ((InternalEList<?>)getSelectors()).basicRemove(otherEnd, msgs);
      case MetamodelPackage.APP__SERIES:
        return ((InternalEList<?>)getSeries()).basicRemove(otherEnd, msgs);
      case MetamodelPackage.APP__STATE_MACHINES:
        return ((InternalEList<?>)getStateMachines()).basicRemove(otherEnd, msgs);
      case MetamodelPackage.APP__EVENTS:
        return ((InternalEList<?>)getEvents()).basicRemove(otherEnd, msgs);
      case MetamodelPackage.APP__APPLICATION_MENUS:
        return ((InternalEList<?>)getApplicationMenus()).basicRemove(otherEnd, msgs);
      case MetamodelPackage.APP__LANGUAGES:
        return ((InternalEList<?>)getLanguages()).basicRemove(otherEnd, msgs);
      case MetamodelPackage.APP__WEB_COMPONENTS:
        return ((InternalEList<?>)getWebComponents()).basicRemove(otherEnd, msgs);
      case MetamodelPackage.APP__TEXT_TEMPLATES:
        return ((InternalEList<?>)getTextTemplates()).basicRemove(otherEnd, msgs);
      case MetamodelPackage.APP__THEMES:
        return ((InternalEList<?>)getThemes()).basicRemove(otherEnd, msgs);
      case MetamodelPackage.APP__AUTHORIZATION_POLICIES:
        return ((InternalEList<?>)getAuthorizationPolicies()).basicRemove(otherEnd, msgs);
      case MetamodelPackage.APP__AUTHORIZATION_ROLES:
        return ((InternalEList<?>)getAuthorizationRoles()).basicRemove(otherEnd, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case MetamodelPackage.APP__AGENTS:
        return getAgents();
      case MetamodelPackage.APP__APPLICATION_BEHAVIOURS:
        return getApplicationBehaviours();
      case MetamodelPackage.APP__COMMITEMENTS:
        return getCommitements();
      case MetamodelPackage.APP__DASHBOARDS:
        return getDashboards();
      case MetamodelPackage.APP__DATASOURCES:
        return getDatasources();
      case MetamodelPackage.APP__DOCUMENTS:
        return getDocuments();
      case MetamodelPackage.APP__ENUMERATIONS:
        return getEnumerations();
      case MetamodelPackage.APP__FORMS:
        return getForms();
      case MetamodelPackage.APP__GENERIC_ENTITIES:
        return getGenericEntities();
      case MetamodelPackage.APP__LISTS:
        return getLists();
      case MetamodelPackage.APP__QUERIES:
        return getQueries();
      case MetamodelPackage.APP__RESOURCES:
        return getResources();
      case MetamodelPackage.APP__SELECTORS:
        return getSelectors();
      case MetamodelPackage.APP__SERIES:
        return getSeries();
      case MetamodelPackage.APP__STATE_MACHINES:
        return getStateMachines();
      case MetamodelPackage.APP__EVENTS:
        return getEvents();
      case MetamodelPackage.APP__APPLICATION_MENUS:
        return getApplicationMenus();
      case MetamodelPackage.APP__LANGUAGES:
        return getLanguages();
      case MetamodelPackage.APP__WEB_COMPONENTS:
        return getWebComponents();
      case MetamodelPackage.APP__TEXT_TEMPLATES:
        return getTextTemplates();
      case MetamodelPackage.APP__THEMES:
        return getThemes();
      case MetamodelPackage.APP__AUTHORIZATION_POLICIES:
        return getAuthorizationPolicies();
      case MetamodelPackage.APP__AUTHORIZATION_ROLES:
        return getAuthorizationRoles();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @SuppressWarnings("unchecked")
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case MetamodelPackage.APP__AGENTS:
        getAgents().clear();
        getAgents().addAll((Collection<? extends Agent>)newValue);
        return;
      case MetamodelPackage.APP__APPLICATION_BEHAVIOURS:
        getApplicationBehaviours().clear();
        getApplicationBehaviours().addAll((Collection<? extends ApplicationBehaviour>)newValue);
        return;
      case MetamodelPackage.APP__COMMITEMENTS:
        getCommitements().clear();
        getCommitements().addAll((Collection<? extends Commitement>)newValue);
        return;
      case MetamodelPackage.APP__DASHBOARDS:
        getDashboards().clear();
        getDashboards().addAll((Collection<? extends Dashboard>)newValue);
        return;
      case MetamodelPackage.APP__DATASOURCES:
        getDatasources().clear();
        getDatasources().addAll((Collection<? extends DataSource>)newValue);
        return;
      case MetamodelPackage.APP__DOCUMENTS:
        getDocuments().clear();
        getDocuments().addAll((Collection<? extends Document>)newValue);
        return;
      case MetamodelPackage.APP__ENUMERATIONS:
        getEnumerations().clear();
        getEnumerations().addAll((Collection<? extends Enumeration>)newValue);
        return;
      case MetamodelPackage.APP__FORMS:
        getForms().clear();
        getForms().addAll((Collection<? extends Form>)newValue);
        return;
      case MetamodelPackage.APP__GENERIC_ENTITIES:
        getGenericEntities().clear();
        getGenericEntities().addAll((Collection<? extends GenericEntity>)newValue);
        return;
      case MetamodelPackage.APP__LISTS:
        getLists().clear();
        getLists().addAll((Collection<? extends List>)newValue);
        return;
      case MetamodelPackage.APP__QUERIES:
        getQueries().clear();
        getQueries().addAll((Collection<? extends Query>)newValue);
        return;
      case MetamodelPackage.APP__RESOURCES:
        getResources().clear();
        getResources().addAll((Collection<? extends Resource>)newValue);
        return;
      case MetamodelPackage.APP__SELECTORS:
        getSelectors().clear();
        getSelectors().addAll((Collection<? extends Selector>)newValue);
        return;
      case MetamodelPackage.APP__SERIES:
        getSeries().clear();
        getSeries().addAll((Collection<? extends Serie>)newValue);
        return;
      case MetamodelPackage.APP__STATE_MACHINES:
        getStateMachines().clear();
        getStateMachines().addAll((Collection<? extends StateMachine>)newValue);
        return;
      case MetamodelPackage.APP__EVENTS:
        getEvents().clear();
        getEvents().addAll((Collection<? extends Event>)newValue);
        return;
      case MetamodelPackage.APP__APPLICATION_MENUS:
        getApplicationMenus().clear();
        getApplicationMenus().addAll((Collection<? extends ApplicationMenu>)newValue);
        return;
      case MetamodelPackage.APP__LANGUAGES:
        getLanguages().clear();
        getLanguages().addAll((Collection<? extends Language>)newValue);
        return;
      case MetamodelPackage.APP__WEB_COMPONENTS:
        getWebComponents().clear();
        getWebComponents().addAll((Collection<? extends WebComponent>)newValue);
        return;
      case MetamodelPackage.APP__TEXT_TEMPLATES:
        getTextTemplates().clear();
        getTextTemplates().addAll((Collection<? extends TextTemplate>)newValue);
        return;
      case MetamodelPackage.APP__THEMES:
        getThemes().clear();
        getThemes().addAll((Collection<? extends Theme>)newValue);
        return;
      case MetamodelPackage.APP__AUTHORIZATION_POLICIES:
        getAuthorizationPolicies().clear();
        getAuthorizationPolicies().addAll((Collection<? extends AuthorizationPolicy>)newValue);
        return;
      case MetamodelPackage.APP__AUTHORIZATION_ROLES:
        getAuthorizationRoles().clear();
        getAuthorizationRoles().addAll((Collection<? extends AuthorizationRole>)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case MetamodelPackage.APP__AGENTS:
        getAgents().clear();
        return;
      case MetamodelPackage.APP__APPLICATION_BEHAVIOURS:
        getApplicationBehaviours().clear();
        return;
      case MetamodelPackage.APP__COMMITEMENTS:
        getCommitements().clear();
        return;
      case MetamodelPackage.APP__DASHBOARDS:
        getDashboards().clear();
        return;
      case MetamodelPackage.APP__DATASOURCES:
        getDatasources().clear();
        return;
      case MetamodelPackage.APP__DOCUMENTS:
        getDocuments().clear();
        return;
      case MetamodelPackage.APP__ENUMERATIONS:
        getEnumerations().clear();
        return;
      case MetamodelPackage.APP__FORMS:
        getForms().clear();
        return;
      case MetamodelPackage.APP__GENERIC_ENTITIES:
        getGenericEntities().clear();
        return;
      case MetamodelPackage.APP__LISTS:
        getLists().clear();
        return;
      case MetamodelPackage.APP__QUERIES:
        getQueries().clear();
        return;
      case MetamodelPackage.APP__RESOURCES:
        getResources().clear();
        return;
      case MetamodelPackage.APP__SELECTORS:
        getSelectors().clear();
        return;
      case MetamodelPackage.APP__SERIES:
        getSeries().clear();
        return;
      case MetamodelPackage.APP__STATE_MACHINES:
        getStateMachines().clear();
        return;
      case MetamodelPackage.APP__EVENTS:
        getEvents().clear();
        return;
      case MetamodelPackage.APP__APPLICATION_MENUS:
        getApplicationMenus().clear();
        return;
      case MetamodelPackage.APP__LANGUAGES:
        getLanguages().clear();
        return;
      case MetamodelPackage.APP__WEB_COMPONENTS:
        getWebComponents().clear();
        return;
      case MetamodelPackage.APP__TEXT_TEMPLATES:
        getTextTemplates().clear();
        return;
      case MetamodelPackage.APP__THEMES:
        getThemes().clear();
        return;
      case MetamodelPackage.APP__AUTHORIZATION_POLICIES:
        getAuthorizationPolicies().clear();
        return;
      case MetamodelPackage.APP__AUTHORIZATION_ROLES:
        getAuthorizationRoles().clear();
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case MetamodelPackage.APP__AGENTS:
        return agents != null && !agents.isEmpty();
      case MetamodelPackage.APP__APPLICATION_BEHAVIOURS:
        return applicationBehaviours != null && !applicationBehaviours.isEmpty();
      case MetamodelPackage.APP__COMMITEMENTS:
        return commitements != null && !commitements.isEmpty();
      case MetamodelPackage.APP__DASHBOARDS:
        return dashboards != null && !dashboards.isEmpty();
      case MetamodelPackage.APP__DATASOURCES:
        return datasources != null && !datasources.isEmpty();
      case MetamodelPackage.APP__DOCUMENTS:
        return documents != null && !documents.isEmpty();
      case MetamodelPackage.APP__ENUMERATIONS:
        return enumerations != null && !enumerations.isEmpty();
      case MetamodelPackage.APP__FORMS:
        return forms != null && !forms.isEmpty();
      case MetamodelPackage.APP__GENERIC_ENTITIES:
        return genericEntities != null && !genericEntities.isEmpty();
      case MetamodelPackage.APP__LISTS:
        return lists != null && !lists.isEmpty();
      case MetamodelPackage.APP__QUERIES:
        return queries != null && !queries.isEmpty();
      case MetamodelPackage.APP__RESOURCES:
        return resources != null && !resources.isEmpty();
      case MetamodelPackage.APP__SELECTORS:
        return selectors != null && !selectors.isEmpty();
      case MetamodelPackage.APP__SERIES:
        return series != null && !series.isEmpty();
      case MetamodelPackage.APP__STATE_MACHINES:
        return stateMachines != null && !stateMachines.isEmpty();
      case MetamodelPackage.APP__EVENTS:
        return events != null && !events.isEmpty();
      case MetamodelPackage.APP__APPLICATION_MENUS:
        return applicationMenus != null && !applicationMenus.isEmpty();
      case MetamodelPackage.APP__LANGUAGES:
        return languages != null && !languages.isEmpty();
      case MetamodelPackage.APP__WEB_COMPONENTS:
        return webComponents != null && !webComponents.isEmpty();
      case MetamodelPackage.APP__TEXT_TEMPLATES:
        return textTemplates != null && !textTemplates.isEmpty();
      case MetamodelPackage.APP__THEMES:
        return themes != null && !themes.isEmpty();
      case MetamodelPackage.APP__AUTHORIZATION_POLICIES:
        return authorizationPolicies != null && !authorizationPolicies.isEmpty();
      case MetamodelPackage.APP__AUTHORIZATION_ROLES:
        return authorizationRoles != null && !authorizationRoles.isEmpty();
    }
    return super.eIsSet(featureID);
  }

} //AppImpl
