/**
 * generated by Xtext 2.27.0
 */
package org.omnia.metamodel.metamodel.impl;

import java.util.Collection;

import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;
import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import org.eclipse.emf.ecore.util.EObjectContainmentEList;
import org.eclipse.emf.ecore.util.InternalEList;

import org.omnia.metamodel.metamodel.ElementAttribute;
import org.omnia.metamodel.metamodel.ElementBehaviour;
import org.omnia.metamodel.metamodel.ElementType;
import org.omnia.metamodel.metamodel.InnerElement;
import org.omnia.metamodel.metamodel.MetamodelPackage;
import org.omnia.metamodel.metamodel.ScreenSize;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Inner Element</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link org.omnia.metamodel.metamodel.impl.InnerElementImpl#isIsHiden <em>Is Hiden</em>}</li>
 *   <li>{@link org.omnia.metamodel.metamodel.impl.InnerElementImpl#getName <em>Name</em>}</li>
 *   <li>{@link org.omnia.metamodel.metamodel.impl.InnerElementImpl#getDescription <em>Description</em>}</li>
 *   <li>{@link org.omnia.metamodel.metamodel.impl.InnerElementImpl#getLabel <em>Label</em>}</li>
 *   <li>{@link org.omnia.metamodel.metamodel.impl.InnerElementImpl#getHelpText <em>Help Text</em>}</li>
 *   <li>{@link org.omnia.metamodel.metamodel.impl.InnerElementImpl#getType <em>Type</em>}</li>
 *   <li>{@link org.omnia.metamodel.metamodel.impl.InnerElementImpl#getRow <em>Row</em>}</li>
 *   <li>{@link org.omnia.metamodel.metamodel.impl.InnerElementImpl#getColumn <em>Column</em>}</li>
 *   <li>{@link org.omnia.metamodel.metamodel.impl.InnerElementImpl#getSize <em>Size</em>}</li>
 *   <li>{@link org.omnia.metamodel.metamodel.impl.InnerElementImpl#getVisibleFrom <em>Visible From</em>}</li>
 *   <li>{@link org.omnia.metamodel.metamodel.impl.InnerElementImpl#getAttributes <em>Attributes</em>}</li>
 *   <li>{@link org.omnia.metamodel.metamodel.impl.InnerElementImpl#getBehaviours <em>Behaviours</em>}</li>
 *   <li>{@link org.omnia.metamodel.metamodel.impl.InnerElementImpl#getElements <em>Elements</em>}</li>
 * </ul>
 *
 * @generated
 */
public class InnerElementImpl extends MinimalEObjectImpl.Container implements InnerElement
{
  /**
   * The default value of the '{@link #isIsHiden() <em>Is Hiden</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #isIsHiden()
   * @generated
   * @ordered
   */
  protected static final boolean IS_HIDEN_EDEFAULT = false;

  /**
   * The cached value of the '{@link #isIsHiden() <em>Is Hiden</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #isIsHiden()
   * @generated
   * @ordered
   */
  protected boolean isHiden = IS_HIDEN_EDEFAULT;

  /**
   * The default value of the '{@link #getName() <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getName()
   * @generated
   * @ordered
   */
  protected static final String NAME_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getName() <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getName()
   * @generated
   * @ordered
   */
  protected String name = NAME_EDEFAULT;

  /**
   * The default value of the '{@link #getDescription() <em>Description</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getDescription()
   * @generated
   * @ordered
   */
  protected static final String DESCRIPTION_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getDescription() <em>Description</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getDescription()
   * @generated
   * @ordered
   */
  protected String description = DESCRIPTION_EDEFAULT;

  /**
   * The default value of the '{@link #getLabel() <em>Label</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getLabel()
   * @generated
   * @ordered
   */
  protected static final String LABEL_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getLabel() <em>Label</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getLabel()
   * @generated
   * @ordered
   */
  protected String label = LABEL_EDEFAULT;

  /**
   * The default value of the '{@link #getHelpText() <em>Help Text</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getHelpText()
   * @generated
   * @ordered
   */
  protected static final String HELP_TEXT_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getHelpText() <em>Help Text</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getHelpText()
   * @generated
   * @ordered
   */
  protected String helpText = HELP_TEXT_EDEFAULT;

  /**
   * The default value of the '{@link #getType() <em>Type</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getType()
   * @generated
   * @ordered
   */
  protected static final ElementType TYPE_EDEFAULT = ElementType.INPUT;

  /**
   * The cached value of the '{@link #getType() <em>Type</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getType()
   * @generated
   * @ordered
   */
  protected ElementType type = TYPE_EDEFAULT;

  /**
   * The default value of the '{@link #getRow() <em>Row</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getRow()
   * @generated
   * @ordered
   */
  protected static final int ROW_EDEFAULT = 0;

  /**
   * The cached value of the '{@link #getRow() <em>Row</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getRow()
   * @generated
   * @ordered
   */
  protected int row = ROW_EDEFAULT;

  /**
   * The default value of the '{@link #getColumn() <em>Column</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getColumn()
   * @generated
   * @ordered
   */
  protected static final int COLUMN_EDEFAULT = 0;

  /**
   * The cached value of the '{@link #getColumn() <em>Column</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getColumn()
   * @generated
   * @ordered
   */
  protected int column = COLUMN_EDEFAULT;

  /**
   * The default value of the '{@link #getSize() <em>Size</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getSize()
   * @generated
   * @ordered
   */
  protected static final int SIZE_EDEFAULT = 0;

  /**
   * The cached value of the '{@link #getSize() <em>Size</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getSize()
   * @generated
   * @ordered
   */
  protected int size = SIZE_EDEFAULT;

  /**
   * The default value of the '{@link #getVisibleFrom() <em>Visible From</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getVisibleFrom()
   * @generated
   * @ordered
   */
  protected static final ScreenSize VISIBLE_FROM_EDEFAULT = ScreenSize.MOBILE;

  /**
   * The cached value of the '{@link #getVisibleFrom() <em>Visible From</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getVisibleFrom()
   * @generated
   * @ordered
   */
  protected ScreenSize visibleFrom = VISIBLE_FROM_EDEFAULT;

  /**
   * The cached value of the '{@link #getAttributes() <em>Attributes</em>}' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getAttributes()
   * @generated
   * @ordered
   */
  protected EList<ElementAttribute> attributes;

  /**
   * The cached value of the '{@link #getBehaviours() <em>Behaviours</em>}' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getBehaviours()
   * @generated
   * @ordered
   */
  protected EList<ElementBehaviour> behaviours;

  /**
   * The cached value of the '{@link #getElements() <em>Elements</em>}' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getElements()
   * @generated
   * @ordered
   */
  protected EList<InnerElement> elements;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected InnerElementImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return MetamodelPackage.Literals.INNER_ELEMENT;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean isIsHiden()
  {
    return isHiden;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setIsHiden(boolean newIsHiden)
  {
    boolean oldIsHiden = isHiden;
    isHiden = newIsHiden;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, MetamodelPackage.INNER_ELEMENT__IS_HIDEN, oldIsHiden, isHiden));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getName()
  {
    return name;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setName(String newName)
  {
    String oldName = name;
    name = newName;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, MetamodelPackage.INNER_ELEMENT__NAME, oldName, name));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getDescription()
  {
    return description;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setDescription(String newDescription)
  {
    String oldDescription = description;
    description = newDescription;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, MetamodelPackage.INNER_ELEMENT__DESCRIPTION, oldDescription, description));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getLabel()
  {
    return label;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setLabel(String newLabel)
  {
    String oldLabel = label;
    label = newLabel;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, MetamodelPackage.INNER_ELEMENT__LABEL, oldLabel, label));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getHelpText()
  {
    return helpText;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setHelpText(String newHelpText)
  {
    String oldHelpText = helpText;
    helpText = newHelpText;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, MetamodelPackage.INNER_ELEMENT__HELP_TEXT, oldHelpText, helpText));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public ElementType getType()
  {
    return type;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setType(ElementType newType)
  {
    ElementType oldType = type;
    type = newType == null ? TYPE_EDEFAULT : newType;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, MetamodelPackage.INNER_ELEMENT__TYPE, oldType, type));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public int getRow()
  {
    return row;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setRow(int newRow)
  {
    int oldRow = row;
    row = newRow;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, MetamodelPackage.INNER_ELEMENT__ROW, oldRow, row));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public int getColumn()
  {
    return column;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setColumn(int newColumn)
  {
    int oldColumn = column;
    column = newColumn;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, MetamodelPackage.INNER_ELEMENT__COLUMN, oldColumn, column));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public int getSize()
  {
    return size;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setSize(int newSize)
  {
    int oldSize = size;
    size = newSize;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, MetamodelPackage.INNER_ELEMENT__SIZE, oldSize, size));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public ScreenSize getVisibleFrom()
  {
    return visibleFrom;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setVisibleFrom(ScreenSize newVisibleFrom)
  {
    ScreenSize oldVisibleFrom = visibleFrom;
    visibleFrom = newVisibleFrom == null ? VISIBLE_FROM_EDEFAULT : newVisibleFrom;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, MetamodelPackage.INNER_ELEMENT__VISIBLE_FROM, oldVisibleFrom, visibleFrom));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EList<ElementAttribute> getAttributes()
  {
    if (attributes == null)
    {
      attributes = new EObjectContainmentEList<ElementAttribute>(ElementAttribute.class, this, MetamodelPackage.INNER_ELEMENT__ATTRIBUTES);
    }
    return attributes;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EList<ElementBehaviour> getBehaviours()
  {
    if (behaviours == null)
    {
      behaviours = new EObjectContainmentEList<ElementBehaviour>(ElementBehaviour.class, this, MetamodelPackage.INNER_ELEMENT__BEHAVIOURS);
    }
    return behaviours;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EList<InnerElement> getElements()
  {
    if (elements == null)
    {
      elements = new EObjectContainmentEList<InnerElement>(InnerElement.class, this, MetamodelPackage.INNER_ELEMENT__ELEMENTS);
    }
    return elements;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case MetamodelPackage.INNER_ELEMENT__ATTRIBUTES:
        return ((InternalEList<?>)getAttributes()).basicRemove(otherEnd, msgs);
      case MetamodelPackage.INNER_ELEMENT__BEHAVIOURS:
        return ((InternalEList<?>)getBehaviours()).basicRemove(otherEnd, msgs);
      case MetamodelPackage.INNER_ELEMENT__ELEMENTS:
        return ((InternalEList<?>)getElements()).basicRemove(otherEnd, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case MetamodelPackage.INNER_ELEMENT__IS_HIDEN:
        return isIsHiden();
      case MetamodelPackage.INNER_ELEMENT__NAME:
        return getName();
      case MetamodelPackage.INNER_ELEMENT__DESCRIPTION:
        return getDescription();
      case MetamodelPackage.INNER_ELEMENT__LABEL:
        return getLabel();
      case MetamodelPackage.INNER_ELEMENT__HELP_TEXT:
        return getHelpText();
      case MetamodelPackage.INNER_ELEMENT__TYPE:
        return getType();
      case MetamodelPackage.INNER_ELEMENT__ROW:
        return getRow();
      case MetamodelPackage.INNER_ELEMENT__COLUMN:
        return getColumn();
      case MetamodelPackage.INNER_ELEMENT__SIZE:
        return getSize();
      case MetamodelPackage.INNER_ELEMENT__VISIBLE_FROM:
        return getVisibleFrom();
      case MetamodelPackage.INNER_ELEMENT__ATTRIBUTES:
        return getAttributes();
      case MetamodelPackage.INNER_ELEMENT__BEHAVIOURS:
        return getBehaviours();
      case MetamodelPackage.INNER_ELEMENT__ELEMENTS:
        return getElements();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @SuppressWarnings("unchecked")
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case MetamodelPackage.INNER_ELEMENT__IS_HIDEN:
        setIsHiden((Boolean)newValue);
        return;
      case MetamodelPackage.INNER_ELEMENT__NAME:
        setName((String)newValue);
        return;
      case MetamodelPackage.INNER_ELEMENT__DESCRIPTION:
        setDescription((String)newValue);
        return;
      case MetamodelPackage.INNER_ELEMENT__LABEL:
        setLabel((String)newValue);
        return;
      case MetamodelPackage.INNER_ELEMENT__HELP_TEXT:
        setHelpText((String)newValue);
        return;
      case MetamodelPackage.INNER_ELEMENT__TYPE:
        setType((ElementType)newValue);
        return;
      case MetamodelPackage.INNER_ELEMENT__ROW:
        setRow((Integer)newValue);
        return;
      case MetamodelPackage.INNER_ELEMENT__COLUMN:
        setColumn((Integer)newValue);
        return;
      case MetamodelPackage.INNER_ELEMENT__SIZE:
        setSize((Integer)newValue);
        return;
      case MetamodelPackage.INNER_ELEMENT__VISIBLE_FROM:
        setVisibleFrom((ScreenSize)newValue);
        return;
      case MetamodelPackage.INNER_ELEMENT__ATTRIBUTES:
        getAttributes().clear();
        getAttributes().addAll((Collection<? extends ElementAttribute>)newValue);
        return;
      case MetamodelPackage.INNER_ELEMENT__BEHAVIOURS:
        getBehaviours().clear();
        getBehaviours().addAll((Collection<? extends ElementBehaviour>)newValue);
        return;
      case MetamodelPackage.INNER_ELEMENT__ELEMENTS:
        getElements().clear();
        getElements().addAll((Collection<? extends InnerElement>)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case MetamodelPackage.INNER_ELEMENT__IS_HIDEN:
        setIsHiden(IS_HIDEN_EDEFAULT);
        return;
      case MetamodelPackage.INNER_ELEMENT__NAME:
        setName(NAME_EDEFAULT);
        return;
      case MetamodelPackage.INNER_ELEMENT__DESCRIPTION:
        setDescription(DESCRIPTION_EDEFAULT);
        return;
      case MetamodelPackage.INNER_ELEMENT__LABEL:
        setLabel(LABEL_EDEFAULT);
        return;
      case MetamodelPackage.INNER_ELEMENT__HELP_TEXT:
        setHelpText(HELP_TEXT_EDEFAULT);
        return;
      case MetamodelPackage.INNER_ELEMENT__TYPE:
        setType(TYPE_EDEFAULT);
        return;
      case MetamodelPackage.INNER_ELEMENT__ROW:
        setRow(ROW_EDEFAULT);
        return;
      case MetamodelPackage.INNER_ELEMENT__COLUMN:
        setColumn(COLUMN_EDEFAULT);
        return;
      case MetamodelPackage.INNER_ELEMENT__SIZE:
        setSize(SIZE_EDEFAULT);
        return;
      case MetamodelPackage.INNER_ELEMENT__VISIBLE_FROM:
        setVisibleFrom(VISIBLE_FROM_EDEFAULT);
        return;
      case MetamodelPackage.INNER_ELEMENT__ATTRIBUTES:
        getAttributes().clear();
        return;
      case MetamodelPackage.INNER_ELEMENT__BEHAVIOURS:
        getBehaviours().clear();
        return;
      case MetamodelPackage.INNER_ELEMENT__ELEMENTS:
        getElements().clear();
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case MetamodelPackage.INNER_ELEMENT__IS_HIDEN:
        return isHiden != IS_HIDEN_EDEFAULT;
      case MetamodelPackage.INNER_ELEMENT__NAME:
        return NAME_EDEFAULT == null ? name != null : !NAME_EDEFAULT.equals(name);
      case MetamodelPackage.INNER_ELEMENT__DESCRIPTION:
        return DESCRIPTION_EDEFAULT == null ? description != null : !DESCRIPTION_EDEFAULT.equals(description);
      case MetamodelPackage.INNER_ELEMENT__LABEL:
        return LABEL_EDEFAULT == null ? label != null : !LABEL_EDEFAULT.equals(label);
      case MetamodelPackage.INNER_ELEMENT__HELP_TEXT:
        return HELP_TEXT_EDEFAULT == null ? helpText != null : !HELP_TEXT_EDEFAULT.equals(helpText);
      case MetamodelPackage.INNER_ELEMENT__TYPE:
        return type != TYPE_EDEFAULT;
      case MetamodelPackage.INNER_ELEMENT__ROW:
        return row != ROW_EDEFAULT;
      case MetamodelPackage.INNER_ELEMENT__COLUMN:
        return column != COLUMN_EDEFAULT;
      case MetamodelPackage.INNER_ELEMENT__SIZE:
        return size != SIZE_EDEFAULT;
      case MetamodelPackage.INNER_ELEMENT__VISIBLE_FROM:
        return visibleFrom != VISIBLE_FROM_EDEFAULT;
      case MetamodelPackage.INNER_ELEMENT__ATTRIBUTES:
        return attributes != null && !attributes.isEmpty();
      case MetamodelPackage.INNER_ELEMENT__BEHAVIOURS:
        return behaviours != null && !behaviours.isEmpty();
      case MetamodelPackage.INNER_ELEMENT__ELEMENTS:
        return elements != null && !elements.isEmpty();
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuilder result = new StringBuilder(super.toString());
    result.append(" (isHiden: ");
    result.append(isHiden);
    result.append(", name: ");
    result.append(name);
    result.append(", description: ");
    result.append(description);
    result.append(", label: ");
    result.append(label);
    result.append(", helpText: ");
    result.append(helpText);
    result.append(", type: ");
    result.append(type);
    result.append(", row: ");
    result.append(row);
    result.append(", column: ");
    result.append(column);
    result.append(", size: ");
    result.append(size);
    result.append(", visibleFrom: ");
    result.append(visibleFrom);
    result.append(')');
    return result.toString();
  }

} //InnerElementImpl
