/**
 * generated by Xtext 2.27.0
 */
package org.omnia.metamodel.metamodel.impl;

import org.eclipse.emf.common.notify.Notification;

import org.eclipse.emf.ecore.EClass;

import org.eclipse.emf.ecore.impl.ENotificationImpl;
import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import org.omnia.metamodel.metamodel.MetamodelPackage;
import org.omnia.metamodel.metamodel.QueryFunction;
import org.omnia.metamodel.metamodel.QueryOrderedProperty;
import org.omnia.metamodel.metamodel.QuerySort;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Query Ordered Property</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link org.omnia.metamodel.metamodel.impl.QueryOrderedPropertyImpl#getPath <em>Path</em>}</li>
 *   <li>{@link org.omnia.metamodel.metamodel.impl.QueryOrderedPropertyImpl#getAlias <em>Alias</em>}</li>
 *   <li>{@link org.omnia.metamodel.metamodel.impl.QueryOrderedPropertyImpl#getFunction <em>Function</em>}</li>
 *   <li>{@link org.omnia.metamodel.metamodel.impl.QueryOrderedPropertyImpl#getDirection <em>Direction</em>}</li>
 * </ul>
 *
 * @generated
 */
public class QueryOrderedPropertyImpl extends MinimalEObjectImpl.Container implements QueryOrderedProperty
{
  /**
   * The default value of the '{@link #getPath() <em>Path</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getPath()
   * @generated
   * @ordered
   */
  protected static final String PATH_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getPath() <em>Path</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getPath()
   * @generated
   * @ordered
   */
  protected String path = PATH_EDEFAULT;

  /**
   * The default value of the '{@link #getAlias() <em>Alias</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getAlias()
   * @generated
   * @ordered
   */
  protected static final String ALIAS_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getAlias() <em>Alias</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getAlias()
   * @generated
   * @ordered
   */
  protected String alias = ALIAS_EDEFAULT;

  /**
   * The default value of the '{@link #getFunction() <em>Function</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getFunction()
   * @generated
   * @ordered
   */
  protected static final QueryFunction FUNCTION_EDEFAULT = QueryFunction.NONE;

  /**
   * The cached value of the '{@link #getFunction() <em>Function</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getFunction()
   * @generated
   * @ordered
   */
  protected QueryFunction function = FUNCTION_EDEFAULT;

  /**
   * The default value of the '{@link #getDirection() <em>Direction</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getDirection()
   * @generated
   * @ordered
   */
  protected static final QuerySort DIRECTION_EDEFAULT = QuerySort.ASCEND;

  /**
   * The cached value of the '{@link #getDirection() <em>Direction</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getDirection()
   * @generated
   * @ordered
   */
  protected QuerySort direction = DIRECTION_EDEFAULT;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected QueryOrderedPropertyImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return MetamodelPackage.Literals.QUERY_ORDERED_PROPERTY;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getPath()
  {
    return path;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setPath(String newPath)
  {
    String oldPath = path;
    path = newPath;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, MetamodelPackage.QUERY_ORDERED_PROPERTY__PATH, oldPath, path));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getAlias()
  {
    return alias;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setAlias(String newAlias)
  {
    String oldAlias = alias;
    alias = newAlias;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, MetamodelPackage.QUERY_ORDERED_PROPERTY__ALIAS, oldAlias, alias));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public QueryFunction getFunction()
  {
    return function;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setFunction(QueryFunction newFunction)
  {
    QueryFunction oldFunction = function;
    function = newFunction == null ? FUNCTION_EDEFAULT : newFunction;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, MetamodelPackage.QUERY_ORDERED_PROPERTY__FUNCTION, oldFunction, function));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public QuerySort getDirection()
  {
    return direction;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setDirection(QuerySort newDirection)
  {
    QuerySort oldDirection = direction;
    direction = newDirection == null ? DIRECTION_EDEFAULT : newDirection;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, MetamodelPackage.QUERY_ORDERED_PROPERTY__DIRECTION, oldDirection, direction));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case MetamodelPackage.QUERY_ORDERED_PROPERTY__PATH:
        return getPath();
      case MetamodelPackage.QUERY_ORDERED_PROPERTY__ALIAS:
        return getAlias();
      case MetamodelPackage.QUERY_ORDERED_PROPERTY__FUNCTION:
        return getFunction();
      case MetamodelPackage.QUERY_ORDERED_PROPERTY__DIRECTION:
        return getDirection();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case MetamodelPackage.QUERY_ORDERED_PROPERTY__PATH:
        setPath((String)newValue);
        return;
      case MetamodelPackage.QUERY_ORDERED_PROPERTY__ALIAS:
        setAlias((String)newValue);
        return;
      case MetamodelPackage.QUERY_ORDERED_PROPERTY__FUNCTION:
        setFunction((QueryFunction)newValue);
        return;
      case MetamodelPackage.QUERY_ORDERED_PROPERTY__DIRECTION:
        setDirection((QuerySort)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case MetamodelPackage.QUERY_ORDERED_PROPERTY__PATH:
        setPath(PATH_EDEFAULT);
        return;
      case MetamodelPackage.QUERY_ORDERED_PROPERTY__ALIAS:
        setAlias(ALIAS_EDEFAULT);
        return;
      case MetamodelPackage.QUERY_ORDERED_PROPERTY__FUNCTION:
        setFunction(FUNCTION_EDEFAULT);
        return;
      case MetamodelPackage.QUERY_ORDERED_PROPERTY__DIRECTION:
        setDirection(DIRECTION_EDEFAULT);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case MetamodelPackage.QUERY_ORDERED_PROPERTY__PATH:
        return PATH_EDEFAULT == null ? path != null : !PATH_EDEFAULT.equals(path);
      case MetamodelPackage.QUERY_ORDERED_PROPERTY__ALIAS:
        return ALIAS_EDEFAULT == null ? alias != null : !ALIAS_EDEFAULT.equals(alias);
      case MetamodelPackage.QUERY_ORDERED_PROPERTY__FUNCTION:
        return function != FUNCTION_EDEFAULT;
      case MetamodelPackage.QUERY_ORDERED_PROPERTY__DIRECTION:
        return direction != DIRECTION_EDEFAULT;
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuilder result = new StringBuilder(super.toString());
    result.append(" (path: ");
    result.append(path);
    result.append(", alias: ");
    result.append(alias);
    result.append(", function: ");
    result.append(function);
    result.append(", direction: ");
    result.append(direction);
    result.append(')');
    return result.toString();
  }

} //QueryOrderedPropertyImpl
