/**
 * generated by Xtext 2.27.0
 */
package org.omnia.metamodel.metamodel;

import org.eclipse.emf.common.util.EList;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Data Source</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.omnia.metamodel.metamodel.DataSource#isExecutesInConnector <em>Executes In Connector</em>}</li>
 *   <li>{@link org.omnia.metamodel.metamodel.DataSource#getName <em>Name</em>}</li>
 *   <li>{@link org.omnia.metamodel.metamodel.DataSource#getDescription <em>Description</em>}</li>
 *   <li>{@link org.omnia.metamodel.metamodel.DataSource#getBehaviourRuntime <em>Behaviour Runtime</em>}</li>
 *   <li>{@link org.omnia.metamodel.metamodel.DataSource#getDataAccessRuntime <em>Data Access Runtime</em>}</li>
 *   <li>{@link org.omnia.metamodel.metamodel.DataSource#getAttributes <em>Attributes</em>}</li>
 *   <li>{@link org.omnia.metamodel.metamodel.DataSource#getEntityBehaviours <em>Entity Behaviours</em>}</li>
 *   <li>{@link org.omnia.metamodel.metamodel.DataSource#getDataBehaviours <em>Data Behaviours</em>}</li>
 *   <li>{@link org.omnia.metamodel.metamodel.DataSource#getBehaviourNamespaces <em>Behaviour Namespaces</em>}</li>
 *   <li>{@link org.omnia.metamodel.metamodel.DataSource#getBehaviourDependencies <em>Behaviour Dependencies</em>}</li>
 * </ul>
 *
 * @see org.omnia.metamodel.metamodel.MetamodelPackage#getDataSource()
 * @model
 * @generated
 */
public interface DataSource extends MType
{
  /**
   * Returns the value of the '<em><b>Executes In Connector</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Executes In Connector</em>' attribute.
   * @see #setExecutesInConnector(boolean)
   * @see org.omnia.metamodel.metamodel.MetamodelPackage#getDataSource_ExecutesInConnector()
   * @model
   * @generated
   */
  boolean isExecutesInConnector();

  /**
   * Sets the value of the '{@link org.omnia.metamodel.metamodel.DataSource#isExecutesInConnector <em>Executes In Connector</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Executes In Connector</em>' attribute.
   * @see #isExecutesInConnector()
   * @generated
   */
  void setExecutesInConnector(boolean value);

  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see org.omnia.metamodel.metamodel.MetamodelPackage#getDataSource_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link org.omnia.metamodel.metamodel.DataSource#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

  /**
   * Returns the value of the '<em><b>Description</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Description</em>' attribute.
   * @see #setDescription(String)
   * @see org.omnia.metamodel.metamodel.MetamodelPackage#getDataSource_Description()
   * @model
   * @generated
   */
  String getDescription();

  /**
   * Sets the value of the '{@link org.omnia.metamodel.metamodel.DataSource#getDescription <em>Description</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Description</em>' attribute.
   * @see #getDescription()
   * @generated
   */
  void setDescription(String value);

  /**
   * Returns the value of the '<em><b>Behaviour Runtime</b></em>' attribute.
   * The literals are from the enumeration {@link org.omnia.metamodel.metamodel.RuntimeLocation}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Behaviour Runtime</em>' attribute.
   * @see org.omnia.metamodel.metamodel.RuntimeLocation
   * @see #setBehaviourRuntime(RuntimeLocation)
   * @see org.omnia.metamodel.metamodel.MetamodelPackage#getDataSource_BehaviourRuntime()
   * @model
   * @generated
   */
  RuntimeLocation getBehaviourRuntime();

  /**
   * Sets the value of the '{@link org.omnia.metamodel.metamodel.DataSource#getBehaviourRuntime <em>Behaviour Runtime</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Behaviour Runtime</em>' attribute.
   * @see org.omnia.metamodel.metamodel.RuntimeLocation
   * @see #getBehaviourRuntime()
   * @generated
   */
  void setBehaviourRuntime(RuntimeLocation value);

  /**
   * Returns the value of the '<em><b>Data Access Runtime</b></em>' attribute.
   * The literals are from the enumeration {@link org.omnia.metamodel.metamodel.RuntimeLocation}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Data Access Runtime</em>' attribute.
   * @see org.omnia.metamodel.metamodel.RuntimeLocation
   * @see #setDataAccessRuntime(RuntimeLocation)
   * @see org.omnia.metamodel.metamodel.MetamodelPackage#getDataSource_DataAccessRuntime()
   * @model
   * @generated
   */
  RuntimeLocation getDataAccessRuntime();

  /**
   * Sets the value of the '{@link org.omnia.metamodel.metamodel.DataSource#getDataAccessRuntime <em>Data Access Runtime</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Data Access Runtime</em>' attribute.
   * @see org.omnia.metamodel.metamodel.RuntimeLocation
   * @see #getDataAccessRuntime()
   * @generated
   */
  void setDataAccessRuntime(RuntimeLocation value);

  /**
   * Returns the value of the '<em><b>Attributes</b></em>' containment reference list.
   * The list contents are of type {@link org.omnia.metamodel.metamodel.MAttribute}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Attributes</em>' containment reference list.
   * @see org.omnia.metamodel.metamodel.MetamodelPackage#getDataSource_Attributes()
   * @model containment="true"
   * @generated
   */
  EList<MAttribute> getAttributes();

  /**
   * Returns the value of the '<em><b>Entity Behaviours</b></em>' containment reference list.
   * The list contents are of type {@link org.omnia.metamodel.metamodel.EntityBehaviour}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Entity Behaviours</em>' containment reference list.
   * @see org.omnia.metamodel.metamodel.MetamodelPackage#getDataSource_EntityBehaviours()
   * @model containment="true"
   * @generated
   */
  EList<EntityBehaviour> getEntityBehaviours();

  /**
   * Returns the value of the '<em><b>Data Behaviours</b></em>' containment reference list.
   * The list contents are of type {@link org.omnia.metamodel.metamodel.DataBehaviour}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Data Behaviours</em>' containment reference list.
   * @see org.omnia.metamodel.metamodel.MetamodelPackage#getDataSource_DataBehaviours()
   * @model containment="true"
   * @generated
   */
  EList<DataBehaviour> getDataBehaviours();

  /**
   * Returns the value of the '<em><b>Behaviour Namespaces</b></em>' containment reference list.
   * The list contents are of type {@link org.omnia.metamodel.metamodel.BehaviourNamespace}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Behaviour Namespaces</em>' containment reference list.
   * @see org.omnia.metamodel.metamodel.MetamodelPackage#getDataSource_BehaviourNamespaces()
   * @model containment="true"
   * @generated
   */
  EList<BehaviourNamespace> getBehaviourNamespaces();

  /**
   * Returns the value of the '<em><b>Behaviour Dependencies</b></em>' containment reference list.
   * The list contents are of type {@link org.omnia.metamodel.metamodel.BehaviourDependency}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Behaviour Dependencies</em>' containment reference list.
   * @see org.omnia.metamodel.metamodel.MetamodelPackage#getDataSource_BehaviourDependencies()
   * @model containment="true"
   * @generated
   */
  EList<BehaviourDependency> getBehaviourDependencies();

} // DataSource
