/**
 * generated by Xtext 2.27.0
 */
package org.omnia.metamodel.metamodel;

import java.util.Arrays;
import java.util.Collections;
import java.util.List;

import org.eclipse.emf.common.util.Enumerator;

/**
 * <!-- begin-user-doc -->
 * A representation of the literals of the enumeration '<em><b>Element Type</b></em>',
 * and utility methods for working with them.
 * <!-- end-user-doc -->
 * @see org.omnia.metamodel.metamodel.MetamodelPackage#getElementType()
 * @model
 * @generated
 */
public enum ElementType implements Enumerator
{
  /**
   * The '<em><b>Input</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #INPUT_VALUE
   * @generated
   * @ordered
   */
  INPUT(0, "Input", "Input"),

  /**
   * The '<em><b>List</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #LIST_VALUE
   * @generated
   * @ordered
   */
  LIST(1, "List", "List"),

  /**
   * The '<em><b>List Column</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #LIST_COLUMN_VALUE
   * @generated
   * @ordered
   */
  LIST_COLUMN(2, "ListColumn", "ListColumn"),

  /**
   * The '<em><b>Group Container</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #GROUP_CONTAINER_VALUE
   * @generated
   * @ordered
   */
  GROUP_CONTAINER(3, "GroupContainer", "GroupContainer"),

  /**
   * The '<em><b>Group</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #GROUP_VALUE
   * @generated
   * @ordered
   */
  GROUP(4, "Group", "Group"),

  /**
   * The '<em><b>Reference Selector</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #REFERENCE_SELECTOR_VALUE
   * @generated
   * @ordered
   */
  REFERENCE_SELECTOR(5, "ReferenceSelector", "ReferenceSelector"),

  /**
   * The '<em><b>Dashboard</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #DASHBOARD_VALUE
   * @generated
   * @ordered
   */
  DASHBOARD(6, "Dashboard", "Dashboard"),

  /**
   * The '<em><b>Form</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #FORM_VALUE
   * @generated
   * @ordered
   */
  FORM(7, "Form", "Form"),

  /**
   * The '<em><b>Web Component</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #WEB_COMPONENT_VALUE
   * @generated
   * @ordered
   */
  WEB_COMPONENT(8, "WebComponent", "WebComponent"),

  /**
   * The '<em><b>Menu</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #MENU_VALUE
   * @generated
   * @ordered
   */
  MENU(9, "Menu", "Menu"),

  /**
   * The '<em><b>Menu Entry</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #MENU_ENTRY_VALUE
   * @generated
   * @ordered
   */
  MENU_ENTRY(10, "MenuEntry", "MenuEntry"),

  /**
   * The '<em><b>Container</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #CONTAINER_VALUE
   * @generated
   * @ordered
   */
  CONTAINER(11, "Container", "Container"),

  /**
   * The '<em><b>Calendar</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #CALENDAR_VALUE
   * @generated
   * @ordered
   */
  CALENDAR(12, "Calendar", "Calendar"),

  /**
   * The '<em><b>Selector</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #SELECTOR_VALUE
   * @generated
   * @ordered
   */
  SELECTOR(13, "Selector", "Selector"),

  /**
   * The '<em><b>Selector Entry</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #SELECTOR_ENTRY_VALUE
   * @generated
   * @ordered
   */
  SELECTOR_ENTRY(14, "SelectorEntry", "SelectorEntry"),

  /**
   * The '<em><b>Button</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #BUTTON_VALUE
   * @generated
   * @ordered
   */
  BUTTON(15, "Button", "Button"),

  /**
   * The '<em><b>Button Group</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #BUTTON_GROUP_VALUE
   * @generated
   * @ordered
   */
  BUTTON_GROUP(16, "ButtonGroup", "ButtonGroup"),

  /**
   * The '<em><b>Label</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #LABEL_VALUE
   * @generated
   * @ordered
   */
  LABEL(17, "Label", "Label"),

  /**
   * The '<em><b>Divider</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #DIVIDER_VALUE
   * @generated
   * @ordered
   */
  DIVIDER(18, "Divider", "Divider"),

  /**
   * The '<em><b>Panel</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #PANEL_VALUE
   * @generated
   * @ordered
   */
  PANEL(19, "Panel", "Panel");

  /**
   * The '<em><b>Input</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #INPUT
   * @model name="Input"
   * @generated
   * @ordered
   */
  public static final int INPUT_VALUE = 0;

  /**
   * The '<em><b>List</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #LIST
   * @model name="List"
   * @generated
   * @ordered
   */
  public static final int LIST_VALUE = 1;

  /**
   * The '<em><b>List Column</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #LIST_COLUMN
   * @model name="ListColumn"
   * @generated
   * @ordered
   */
  public static final int LIST_COLUMN_VALUE = 2;

  /**
   * The '<em><b>Group Container</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #GROUP_CONTAINER
   * @model name="GroupContainer"
   * @generated
   * @ordered
   */
  public static final int GROUP_CONTAINER_VALUE = 3;

  /**
   * The '<em><b>Group</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #GROUP
   * @model name="Group"
   * @generated
   * @ordered
   */
  public static final int GROUP_VALUE = 4;

  /**
   * The '<em><b>Reference Selector</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #REFERENCE_SELECTOR
   * @model name="ReferenceSelector"
   * @generated
   * @ordered
   */
  public static final int REFERENCE_SELECTOR_VALUE = 5;

  /**
   * The '<em><b>Dashboard</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #DASHBOARD
   * @model name="Dashboard"
   * @generated
   * @ordered
   */
  public static final int DASHBOARD_VALUE = 6;

  /**
   * The '<em><b>Form</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #FORM
   * @model name="Form"
   * @generated
   * @ordered
   */
  public static final int FORM_VALUE = 7;

  /**
   * The '<em><b>Web Component</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #WEB_COMPONENT
   * @model name="WebComponent"
   * @generated
   * @ordered
   */
  public static final int WEB_COMPONENT_VALUE = 8;

  /**
   * The '<em><b>Menu</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #MENU
   * @model name="Menu"
   * @generated
   * @ordered
   */
  public static final int MENU_VALUE = 9;

  /**
   * The '<em><b>Menu Entry</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #MENU_ENTRY
   * @model name="MenuEntry"
   * @generated
   * @ordered
   */
  public static final int MENU_ENTRY_VALUE = 10;

  /**
   * The '<em><b>Container</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #CONTAINER
   * @model name="Container"
   * @generated
   * @ordered
   */
  public static final int CONTAINER_VALUE = 11;

  /**
   * The '<em><b>Calendar</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #CALENDAR
   * @model name="Calendar"
   * @generated
   * @ordered
   */
  public static final int CALENDAR_VALUE = 12;

  /**
   * The '<em><b>Selector</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #SELECTOR
   * @model name="Selector"
   * @generated
   * @ordered
   */
  public static final int SELECTOR_VALUE = 13;

  /**
   * The '<em><b>Selector Entry</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #SELECTOR_ENTRY
   * @model name="SelectorEntry"
   * @generated
   * @ordered
   */
  public static final int SELECTOR_ENTRY_VALUE = 14;

  /**
   * The '<em><b>Button</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #BUTTON
   * @model name="Button"
   * @generated
   * @ordered
   */
  public static final int BUTTON_VALUE = 15;

  /**
   * The '<em><b>Button Group</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #BUTTON_GROUP
   * @model name="ButtonGroup"
   * @generated
   * @ordered
   */
  public static final int BUTTON_GROUP_VALUE = 16;

  /**
   * The '<em><b>Label</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #LABEL
   * @model name="Label"
   * @generated
   * @ordered
   */
  public static final int LABEL_VALUE = 17;

  /**
   * The '<em><b>Divider</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #DIVIDER
   * @model name="Divider"
   * @generated
   * @ordered
   */
  public static final int DIVIDER_VALUE = 18;

  /**
   * The '<em><b>Panel</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #PANEL
   * @model name="Panel"
   * @generated
   * @ordered
   */
  public static final int PANEL_VALUE = 19;

  /**
   * An array of all the '<em><b>Element Type</b></em>' enumerators.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private static final ElementType[] VALUES_ARRAY =
    new ElementType[]
    {
      INPUT,
      LIST,
      LIST_COLUMN,
      GROUP_CONTAINER,
      GROUP,
      REFERENCE_SELECTOR,
      DASHBOARD,
      FORM,
      WEB_COMPONENT,
      MENU,
      MENU_ENTRY,
      CONTAINER,
      CALENDAR,
      SELECTOR,
      SELECTOR_ENTRY,
      BUTTON,
      BUTTON_GROUP,
      LABEL,
      DIVIDER,
      PANEL,
    };

  /**
   * A public read-only list of all the '<em><b>Element Type</b></em>' enumerators.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public static final List<ElementType> VALUES = Collections.unmodifiableList(Arrays.asList(VALUES_ARRAY));

  /**
   * Returns the '<em><b>Element Type</b></em>' literal with the specified literal value.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param literal the literal.
   * @return the matching enumerator or <code>null</code>.
   * @generated
   */
  public static ElementType get(String literal)
  {
    for (int i = 0; i < VALUES_ARRAY.length; ++i)
    {
      ElementType result = VALUES_ARRAY[i];
      if (result.toString().equals(literal))
      {
        return result;
      }
    }
    return null;
  }

  /**
   * Returns the '<em><b>Element Type</b></em>' literal with the specified name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param name the name.
   * @return the matching enumerator or <code>null</code>.
   * @generated
   */
  public static ElementType getByName(String name)
  {
    for (int i = 0; i < VALUES_ARRAY.length; ++i)
    {
      ElementType result = VALUES_ARRAY[i];
      if (result.getName().equals(name))
      {
        return result;
      }
    }
    return null;
  }

  /**
   * Returns the '<em><b>Element Type</b></em>' literal with the specified integer value.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the integer value.
   * @return the matching enumerator or <code>null</code>.
   * @generated
   */
  public static ElementType get(int value)
  {
    switch (value)
    {
      case INPUT_VALUE: return INPUT;
      case LIST_VALUE: return LIST;
      case LIST_COLUMN_VALUE: return LIST_COLUMN;
      case GROUP_CONTAINER_VALUE: return GROUP_CONTAINER;
      case GROUP_VALUE: return GROUP;
      case REFERENCE_SELECTOR_VALUE: return REFERENCE_SELECTOR;
      case DASHBOARD_VALUE: return DASHBOARD;
      case FORM_VALUE: return FORM;
      case WEB_COMPONENT_VALUE: return WEB_COMPONENT;
      case MENU_VALUE: return MENU;
      case MENU_ENTRY_VALUE: return MENU_ENTRY;
      case CONTAINER_VALUE: return CONTAINER;
      case CALENDAR_VALUE: return CALENDAR;
      case SELECTOR_VALUE: return SELECTOR;
      case SELECTOR_ENTRY_VALUE: return SELECTOR_ENTRY;
      case BUTTON_VALUE: return BUTTON;
      case BUTTON_GROUP_VALUE: return BUTTON_GROUP;
      case LABEL_VALUE: return LABEL;
      case DIVIDER_VALUE: return DIVIDER;
      case PANEL_VALUE: return PANEL;
    }
    return null;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private final int value;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private final String name;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private final String literal;

  /**
   * Only this class can construct instances.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private ElementType(int value, String name, String literal)
  {
    this.value = value;
    this.name = name;
    this.literal = literal;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public int getValue()
  {
    return value;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getName()
  {
    return name;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getLiteral()
  {
    return literal;
  }

  /**
   * Returns the literal value of the enumerator, which is its string representation.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    return literal;
  }
  
} //ElementType
