/**
 * generated by Xtext 2.27.0
 */
package org.omnia.metamodel.metamodel;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Inner Element</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.omnia.metamodel.metamodel.InnerElement#isIsHiden <em>Is Hiden</em>}</li>
 *   <li>{@link org.omnia.metamodel.metamodel.InnerElement#getName <em>Name</em>}</li>
 *   <li>{@link org.omnia.metamodel.metamodel.InnerElement#getDescription <em>Description</em>}</li>
 *   <li>{@link org.omnia.metamodel.metamodel.InnerElement#getLabel <em>Label</em>}</li>
 *   <li>{@link org.omnia.metamodel.metamodel.InnerElement#getHelpText <em>Help Text</em>}</li>
 *   <li>{@link org.omnia.metamodel.metamodel.InnerElement#getType <em>Type</em>}</li>
 *   <li>{@link org.omnia.metamodel.metamodel.InnerElement#getRow <em>Row</em>}</li>
 *   <li>{@link org.omnia.metamodel.metamodel.InnerElement#getColumn <em>Column</em>}</li>
 *   <li>{@link org.omnia.metamodel.metamodel.InnerElement#getSize <em>Size</em>}</li>
 *   <li>{@link org.omnia.metamodel.metamodel.InnerElement#getVisibleFrom <em>Visible From</em>}</li>
 *   <li>{@link org.omnia.metamodel.metamodel.InnerElement#getAttributes <em>Attributes</em>}</li>
 *   <li>{@link org.omnia.metamodel.metamodel.InnerElement#getBehaviours <em>Behaviours</em>}</li>
 *   <li>{@link org.omnia.metamodel.metamodel.InnerElement#getElements <em>Elements</em>}</li>
 * </ul>
 *
 * @see org.omnia.metamodel.metamodel.MetamodelPackage#getInnerElement()
 * @model
 * @generated
 */
public interface InnerElement extends EObject
{
  /**
   * Returns the value of the '<em><b>Is Hiden</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Is Hiden</em>' attribute.
   * @see #setIsHiden(boolean)
   * @see org.omnia.metamodel.metamodel.MetamodelPackage#getInnerElement_IsHiden()
   * @model
   * @generated
   */
  boolean isIsHiden();

  /**
   * Sets the value of the '{@link org.omnia.metamodel.metamodel.InnerElement#isIsHiden <em>Is Hiden</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Is Hiden</em>' attribute.
   * @see #isIsHiden()
   * @generated
   */
  void setIsHiden(boolean value);

  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see org.omnia.metamodel.metamodel.MetamodelPackage#getInnerElement_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link org.omnia.metamodel.metamodel.InnerElement#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

  /**
   * Returns the value of the '<em><b>Description</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Description</em>' attribute.
   * @see #setDescription(String)
   * @see org.omnia.metamodel.metamodel.MetamodelPackage#getInnerElement_Description()
   * @model
   * @generated
   */
  String getDescription();

  /**
   * Sets the value of the '{@link org.omnia.metamodel.metamodel.InnerElement#getDescription <em>Description</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Description</em>' attribute.
   * @see #getDescription()
   * @generated
   */
  void setDescription(String value);

  /**
   * Returns the value of the '<em><b>Label</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Label</em>' attribute.
   * @see #setLabel(String)
   * @see org.omnia.metamodel.metamodel.MetamodelPackage#getInnerElement_Label()
   * @model
   * @generated
   */
  String getLabel();

  /**
   * Sets the value of the '{@link org.omnia.metamodel.metamodel.InnerElement#getLabel <em>Label</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Label</em>' attribute.
   * @see #getLabel()
   * @generated
   */
  void setLabel(String value);

  /**
   * Returns the value of the '<em><b>Help Text</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Help Text</em>' attribute.
   * @see #setHelpText(String)
   * @see org.omnia.metamodel.metamodel.MetamodelPackage#getInnerElement_HelpText()
   * @model
   * @generated
   */
  String getHelpText();

  /**
   * Sets the value of the '{@link org.omnia.metamodel.metamodel.InnerElement#getHelpText <em>Help Text</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Help Text</em>' attribute.
   * @see #getHelpText()
   * @generated
   */
  void setHelpText(String value);

  /**
   * Returns the value of the '<em><b>Type</b></em>' attribute.
   * The literals are from the enumeration {@link org.omnia.metamodel.metamodel.ElementType}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Type</em>' attribute.
   * @see org.omnia.metamodel.metamodel.ElementType
   * @see #setType(ElementType)
   * @see org.omnia.metamodel.metamodel.MetamodelPackage#getInnerElement_Type()
   * @model
   * @generated
   */
  ElementType getType();

  /**
   * Sets the value of the '{@link org.omnia.metamodel.metamodel.InnerElement#getType <em>Type</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Type</em>' attribute.
   * @see org.omnia.metamodel.metamodel.ElementType
   * @see #getType()
   * @generated
   */
  void setType(ElementType value);

  /**
   * Returns the value of the '<em><b>Row</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Row</em>' attribute.
   * @see #setRow(int)
   * @see org.omnia.metamodel.metamodel.MetamodelPackage#getInnerElement_Row()
   * @model
   * @generated
   */
  int getRow();

  /**
   * Sets the value of the '{@link org.omnia.metamodel.metamodel.InnerElement#getRow <em>Row</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Row</em>' attribute.
   * @see #getRow()
   * @generated
   */
  void setRow(int value);

  /**
   * Returns the value of the '<em><b>Column</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Column</em>' attribute.
   * @see #setColumn(int)
   * @see org.omnia.metamodel.metamodel.MetamodelPackage#getInnerElement_Column()
   * @model
   * @generated
   */
  int getColumn();

  /**
   * Sets the value of the '{@link org.omnia.metamodel.metamodel.InnerElement#getColumn <em>Column</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Column</em>' attribute.
   * @see #getColumn()
   * @generated
   */
  void setColumn(int value);

  /**
   * Returns the value of the '<em><b>Size</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Size</em>' attribute.
   * @see #setSize(int)
   * @see org.omnia.metamodel.metamodel.MetamodelPackage#getInnerElement_Size()
   * @model
   * @generated
   */
  int getSize();

  /**
   * Sets the value of the '{@link org.omnia.metamodel.metamodel.InnerElement#getSize <em>Size</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Size</em>' attribute.
   * @see #getSize()
   * @generated
   */
  void setSize(int value);

  /**
   * Returns the value of the '<em><b>Visible From</b></em>' attribute.
   * The literals are from the enumeration {@link org.omnia.metamodel.metamodel.ScreenSize}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Visible From</em>' attribute.
   * @see org.omnia.metamodel.metamodel.ScreenSize
   * @see #setVisibleFrom(ScreenSize)
   * @see org.omnia.metamodel.metamodel.MetamodelPackage#getInnerElement_VisibleFrom()
   * @model
   * @generated
   */
  ScreenSize getVisibleFrom();

  /**
   * Sets the value of the '{@link org.omnia.metamodel.metamodel.InnerElement#getVisibleFrom <em>Visible From</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Visible From</em>' attribute.
   * @see org.omnia.metamodel.metamodel.ScreenSize
   * @see #getVisibleFrom()
   * @generated
   */
  void setVisibleFrom(ScreenSize value);

  /**
   * Returns the value of the '<em><b>Attributes</b></em>' containment reference list.
   * The list contents are of type {@link org.omnia.metamodel.metamodel.ElementAttribute}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Attributes</em>' containment reference list.
   * @see org.omnia.metamodel.metamodel.MetamodelPackage#getInnerElement_Attributes()
   * @model containment="true"
   * @generated
   */
  EList<ElementAttribute> getAttributes();

  /**
   * Returns the value of the '<em><b>Behaviours</b></em>' containment reference list.
   * The list contents are of type {@link org.omnia.metamodel.metamodel.ElementBehaviour}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Behaviours</em>' containment reference list.
   * @see org.omnia.metamodel.metamodel.MetamodelPackage#getInnerElement_Behaviours()
   * @model containment="true"
   * @generated
   */
  EList<ElementBehaviour> getBehaviours();

  /**
   * Returns the value of the '<em><b>Elements</b></em>' containment reference list.
   * The list contents are of type {@link org.omnia.metamodel.metamodel.InnerElement}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Elements</em>' containment reference list.
   * @see org.omnia.metamodel.metamodel.MetamodelPackage#getInnerElement_Elements()
   * @model containment="true"
   * @generated
   */
  EList<InnerElement> getElements();

} // InnerElement
