/**
 * generated by Xtext 2.27.0
 */
package org.omnia.metamodel.metamodel;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>MAttribute</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.omnia.metamodel.metamodel.MAttribute#isIsSystem <em>Is System</em>}</li>
 *   <li>{@link org.omnia.metamodel.metamodel.MAttribute#isIsReadOnly <em>Is Read Only</em>}</li>
 *   <li>{@link org.omnia.metamodel.metamodel.MAttribute#isIsSensitiveData <em>Is Sensitive Data</em>}</li>
 *   <li>{@link org.omnia.metamodel.metamodel.MAttribute#getName <em>Name</em>}</li>
 *   <li>{@link org.omnia.metamodel.metamodel.MAttribute#getDescription <em>Description</em>}</li>
 *   <li>{@link org.omnia.metamodel.metamodel.MAttribute#getAggregationKind <em>Aggregation Kind</em>}</li>
 *   <li>{@link org.omnia.metamodel.metamodel.MAttribute#getType <em>Type</em>}</li>
 *   <li>{@link org.omnia.metamodel.metamodel.MAttribute#getDependsOnAttribute <em>Depends On Attribute</em>}</li>
 *   <li>{@link org.omnia.metamodel.metamodel.MAttribute#getMultiplicity <em>Multiplicity</em>}</li>
 * </ul>
 *
 * @see org.omnia.metamodel.metamodel.MetamodelPackage#getMAttribute()
 * @model
 * @generated
 */
public interface MAttribute extends EObject
{
  /**
   * Returns the value of the '<em><b>Is System</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Is System</em>' attribute.
   * @see #setIsSystem(boolean)
   * @see org.omnia.metamodel.metamodel.MetamodelPackage#getMAttribute_IsSystem()
   * @model
   * @generated
   */
  boolean isIsSystem();

  /**
   * Sets the value of the '{@link org.omnia.metamodel.metamodel.MAttribute#isIsSystem <em>Is System</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Is System</em>' attribute.
   * @see #isIsSystem()
   * @generated
   */
  void setIsSystem(boolean value);

  /**
   * Returns the value of the '<em><b>Is Read Only</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Is Read Only</em>' attribute.
   * @see #setIsReadOnly(boolean)
   * @see org.omnia.metamodel.metamodel.MetamodelPackage#getMAttribute_IsReadOnly()
   * @model
   * @generated
   */
  boolean isIsReadOnly();

  /**
   * Sets the value of the '{@link org.omnia.metamodel.metamodel.MAttribute#isIsReadOnly <em>Is Read Only</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Is Read Only</em>' attribute.
   * @see #isIsReadOnly()
   * @generated
   */
  void setIsReadOnly(boolean value);

  /**
   * Returns the value of the '<em><b>Is Sensitive Data</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Is Sensitive Data</em>' attribute.
   * @see #setIsSensitiveData(boolean)
   * @see org.omnia.metamodel.metamodel.MetamodelPackage#getMAttribute_IsSensitiveData()
   * @model
   * @generated
   */
  boolean isIsSensitiveData();

  /**
   * Sets the value of the '{@link org.omnia.metamodel.metamodel.MAttribute#isIsSensitiveData <em>Is Sensitive Data</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Is Sensitive Data</em>' attribute.
   * @see #isIsSensitiveData()
   * @generated
   */
  void setIsSensitiveData(boolean value);

  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see org.omnia.metamodel.metamodel.MetamodelPackage#getMAttribute_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link org.omnia.metamodel.metamodel.MAttribute#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

  /**
   * Returns the value of the '<em><b>Description</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Description</em>' attribute.
   * @see #setDescription(String)
   * @see org.omnia.metamodel.metamodel.MetamodelPackage#getMAttribute_Description()
   * @model
   * @generated
   */
  String getDescription();

  /**
   * Sets the value of the '{@link org.omnia.metamodel.metamodel.MAttribute#getDescription <em>Description</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Description</em>' attribute.
   * @see #getDescription()
   * @generated
   */
  void setDescription(String value);

  /**
   * Returns the value of the '<em><b>Aggregation Kind</b></em>' attribute.
   * The literals are from the enumeration {@link org.omnia.metamodel.metamodel.MAggregationKind}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Aggregation Kind</em>' attribute.
   * @see org.omnia.metamodel.metamodel.MAggregationKind
   * @see #setAggregationKind(MAggregationKind)
   * @see org.omnia.metamodel.metamodel.MetamodelPackage#getMAttribute_AggregationKind()
   * @model
   * @generated
   */
  MAggregationKind getAggregationKind();

  /**
   * Sets the value of the '{@link org.omnia.metamodel.metamodel.MAttribute#getAggregationKind <em>Aggregation Kind</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Aggregation Kind</em>' attribute.
   * @see org.omnia.metamodel.metamodel.MAggregationKind
   * @see #getAggregationKind()
   * @generated
   */
  void setAggregationKind(MAggregationKind value);

  /**
   * Returns the value of the '<em><b>Type</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Type</em>' reference.
   * @see #setType(MType)
   * @see org.omnia.metamodel.metamodel.MetamodelPackage#getMAttribute_Type()
   * @model
   * @generated
   */
  MType getType();

  /**
   * Sets the value of the '{@link org.omnia.metamodel.metamodel.MAttribute#getType <em>Type</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Type</em>' reference.
   * @see #getType()
   * @generated
   */
  void setType(MType value);

  /**
   * Returns the value of the '<em><b>Depends On Attribute</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Depends On Attribute</em>' reference.
   * @see #setDependsOnAttribute(MAttribute)
   * @see org.omnia.metamodel.metamodel.MetamodelPackage#getMAttribute_DependsOnAttribute()
   * @model
   * @generated
   */
  MAttribute getDependsOnAttribute();

  /**
   * Sets the value of the '{@link org.omnia.metamodel.metamodel.MAttribute#getDependsOnAttribute <em>Depends On Attribute</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Depends On Attribute</em>' reference.
   * @see #getDependsOnAttribute()
   * @generated
   */
  void setDependsOnAttribute(MAttribute value);

  /**
   * Returns the value of the '<em><b>Multiplicity</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Multiplicity</em>' containment reference.
   * @see #setMultiplicity(MMultiplicity)
   * @see org.omnia.metamodel.metamodel.MetamodelPackage#getMAttribute_Multiplicity()
   * @model containment="true"
   * @generated
   */
  MMultiplicity getMultiplicity();

  /**
   * Sets the value of the '{@link org.omnia.metamodel.metamodel.MAttribute#getMultiplicity <em>Multiplicity</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Multiplicity</em>' containment reference.
   * @see #getMultiplicity()
   * @generated
   */
  void setMultiplicity(MMultiplicity value);

} // MAttribute
