/**
 * generated by Xtext 2.27.0
 */
package org.omnia.metamodel.metamodel;

import org.eclipse.emf.ecore.EFactory;

/**
 * <!-- begin-user-doc -->
 * The <b>Factory</b> for the model.
 * It provides a create method for each non-abstract class of the model.
 * <!-- end-user-doc -->
 * @see org.omnia.metamodel.metamodel.MetamodelPackage
 * @generated
 */
public interface MetamodelFactory extends EFactory
{
  /**
   * The singleton instance of the factory.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  MetamodelFactory eINSTANCE = org.omnia.metamodel.metamodel.impl.MetamodelFactoryImpl.init();

  /**
   * Returns a new object of class '<em>App</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>App</em>'.
   * @generated
   */
  App createApp();

  /**
   * Returns a new object of class '<em>Entity</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Entity</em>'.
   * @generated
   */
  Entity createEntity();

  /**
   * Returns a new object of class '<em>MType</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>MType</em>'.
   * @generated
   */
  MType createMType();

  /**
   * Returns a new object of class '<em>Agent</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Agent</em>'.
   * @generated
   */
  Agent createAgent();

  /**
   * Returns a new object of class '<em>Application Behaviour</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Application Behaviour</em>'.
   * @generated
   */
  ApplicationBehaviour createApplicationBehaviour();

  /**
   * Returns a new object of class '<em>Commitement</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Commitement</em>'.
   * @generated
   */
  Commitement createCommitement();

  /**
   * Returns a new object of class '<em>Dashboard</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Dashboard</em>'.
   * @generated
   */
  Dashboard createDashboard();

  /**
   * Returns a new object of class '<em>Data Source</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Data Source</em>'.
   * @generated
   */
  DataSource createDataSource();

  /**
   * Returns a new object of class '<em>Document</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Document</em>'.
   * @generated
   */
  Document createDocument();

  /**
   * Returns a new object of class '<em>Enumeration</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Enumeration</em>'.
   * @generated
   */
  Enumeration createEnumeration();

  /**
   * Returns a new object of class '<em>Form</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Form</em>'.
   * @generated
   */
  Form createForm();

  /**
   * Returns a new object of class '<em>Generic Entity</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Generic Entity</em>'.
   * @generated
   */
  GenericEntity createGenericEntity();

  /**
   * Returns a new object of class '<em>List</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>List</em>'.
   * @generated
   */
  List createList();

  /**
   * Returns a new object of class '<em>Query</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Query</em>'.
   * @generated
   */
  Query createQuery();

  /**
   * Returns a new object of class '<em>Resource</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Resource</em>'.
   * @generated
   */
  Resource createResource();

  /**
   * Returns a new object of class '<em>Selector</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Selector</em>'.
   * @generated
   */
  Selector createSelector();

  /**
   * Returns a new object of class '<em>Serie</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Serie</em>'.
   * @generated
   */
  Serie createSerie();

  /**
   * Returns a new object of class '<em>State Machine</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>State Machine</em>'.
   * @generated
   */
  StateMachine createStateMachine();

  /**
   * Returns a new object of class '<em>Event</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Event</em>'.
   * @generated
   */
  Event createEvent();

  /**
   * Returns a new object of class '<em>Application Menu</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Application Menu</em>'.
   * @generated
   */
  ApplicationMenu createApplicationMenu();

  /**
   * Returns a new object of class '<em>Language</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Language</em>'.
   * @generated
   */
  Language createLanguage();

  /**
   * Returns a new object of class '<em>Web Component</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Web Component</em>'.
   * @generated
   */
  WebComponent createWebComponent();

  /**
   * Returns a new object of class '<em>Text Template</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Text Template</em>'.
   * @generated
   */
  TextTemplate createTextTemplate();

  /**
   * Returns a new object of class '<em>Theme</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Theme</em>'.
   * @generated
   */
  Theme createTheme();

  /**
   * Returns a new object of class '<em>Authorization Policy</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Authorization Policy</em>'.
   * @generated
   */
  AuthorizationPolicy createAuthorizationPolicy();

  /**
   * Returns a new object of class '<em>Authorization Role</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Authorization Role</em>'.
   * @generated
   */
  AuthorizationRole createAuthorizationRole();

  /**
   * Returns a new object of class '<em>MAttribute</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>MAttribute</em>'.
   * @generated
   */
  MAttribute createMAttribute();

  /**
   * Returns a new object of class '<em>Entity Behaviour</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Entity Behaviour</em>'.
   * @generated
   */
  EntityBehaviour createEntityBehaviour();

  /**
   * Returns a new object of class '<em>Data Behaviour</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Data Behaviour</em>'.
   * @generated
   */
  DataBehaviour createDataBehaviour();

  /**
   * Returns a new object of class '<em>Behaviour Namespace</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Behaviour Namespace</em>'.
   * @generated
   */
  BehaviourNamespace createBehaviourNamespace();

  /**
   * Returns a new object of class '<em>MMultiplicity</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>MMultiplicity</em>'.
   * @generated
   */
  MMultiplicity createMMultiplicity();

  /**
   * Returns a new object of class '<em>MEnumeration</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>MEnumeration</em>'.
   * @generated
   */
  MEnumeration createMEnumeration();

  /**
   * Returns a new object of class '<em>MBoolean</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>MBoolean</em>'.
   * @generated
   */
  MBoolean createMBoolean();

  /**
   * Returns a new object of class '<em>MDate</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>MDate</em>'.
   * @generated
   */
  MDate createMDate();

  /**
   * Returns a new object of class '<em>MDecimal</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>MDecimal</em>'.
   * @generated
   */
  MDecimal createMDecimal();

  /**
   * Returns a new object of class '<em>MInteger</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>MInteger</em>'.
   * @generated
   */
  MInteger createMInteger();

  /**
   * Returns a new object of class '<em>MText</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>MText</em>'.
   * @generated
   */
  MText createMText();

  /**
   * Returns a new object of class '<em>MUuid</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>MUuid</em>'.
   * @generated
   */
  MUuid createMUuid();

  /**
   * Returns a new object of class '<em>Element Attribute</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Element Attribute</em>'.
   * @generated
   */
  ElementAttribute createElementAttribute();

  /**
   * Returns a new object of class '<em>Element Behaviour</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Element Behaviour</em>'.
   * @generated
   */
  ElementBehaviour createElementBehaviour();

  /**
   * Returns a new object of class '<em>Inner Element</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Inner Element</em>'.
   * @generated
   */
  InnerElement createInnerElement();

  /**
   * Returns a new object of class '<em>Behaviour Dependency</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Behaviour Dependency</em>'.
   * @generated
   */
  BehaviourDependency createBehaviourDependency();

  /**
   * Returns a new object of class '<em>Enumeration Value</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Enumeration Value</em>'.
   * @generated
   */
  EnumerationValue createEnumerationValue();

  /**
   * Returns a new object of class '<em>Query Table</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Query Table</em>'.
   * @generated
   */
  QueryTable createQueryTable();

  /**
   * Returns a new object of class '<em>Query Join</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Query Join</em>'.
   * @generated
   */
  QueryJoin createQueryJoin();

  /**
   * Returns a new object of class '<em>Query Property</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Query Property</em>'.
   * @generated
   */
  QueryProperty createQueryProperty();

  /**
   * Returns a new object of class '<em>Query Ordered Property</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Query Ordered Property</em>'.
   * @generated
   */
  QueryOrderedProperty createQueryOrderedProperty();

  /**
   * Returns a new object of class '<em>Query Filter</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Query Filter</em>'.
   * @generated
   */
  QueryFilter createQueryFilter();

  /**
   * Returns a new object of class '<em>Query Join Predicate</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Query Join Predicate</em>'.
   * @generated
   */
  QueryJoinPredicate createQueryJoinPredicate();

  /**
   * Returns a new object of class '<em>State</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>State</em>'.
   * @generated
   */
  State createState();

  /**
   * Returns a new object of class '<em>State Transition</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>State Transition</em>'.
   * @generated
   */
  StateTransition createStateTransition();

  /**
   * Returns a new object of class '<em>State Decision</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>State Decision</em>'.
   * @generated
   */
  StateDecision createStateDecision();

  /**
   * Returns a new object of class '<em>State Enabled Operation</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>State Enabled Operation</em>'.
   * @generated
   */
  StateEnabledOperation createStateEnabledOperation();

  /**
   * Returns a new object of class '<em>State Enabled Attribute</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>State Enabled Attribute</em>'.
   * @generated
   */
  StateEnabledAttribute createStateEnabledAttribute();

  /**
   * Returns a new object of class '<em>State Behaviour</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>State Behaviour</em>'.
   * @generated
   */
  StateBehaviour createStateBehaviour();

  /**
   * Returns a new object of class '<em>Language Text</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Language Text</em>'.
   * @generated
   */
  LanguageText createLanguageText();

  /**
   * Returns a new object of class '<em>Authorization Policy Permission</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Authorization Policy Permission</em>'.
   * @generated
   */
  AuthorizationPolicyPermission createAuthorizationPolicyPermission();

  /**
   * Returns a new object of class '<em>Authorization Role Subject</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Authorization Role Subject</em>'.
   * @generated
   */
  AuthorizationRoleSubject createAuthorizationRoleSubject();

  /**
   * Returns the package supported by this factory.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the package supported by this factory.
   * @generated
   */
  MetamodelPackage getMetamodelPackage();

} //MetamodelFactory
