/**
 * generated by Xtext 2.27.0
 */
package org.omnia.metamodel.metamodel;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Query Filter</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see org.omnia.metamodel.metamodel.MetamodelPackage#getQueryFilter()
 * @model
 * @generated
 */
public interface QueryFilter extends EObject
{
} // QueryFilter
