/**
 * generated by Xtext 2.27.0
 */
package org.omnia.metamodel.metamodel;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Query</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.omnia.metamodel.metamodel.Query#getName <em>Name</em>}</li>
 *   <li>{@link org.omnia.metamodel.metamodel.Query#getDescription <em>Description</em>}</li>
 *   <li>{@link org.omnia.metamodel.metamodel.Query#getExpression <em>Expression</em>}</li>
 *   <li>{@link org.omnia.metamodel.metamodel.Query#getDataSource <em>Data Source</em>}</li>
 *   <li>{@link org.omnia.metamodel.metamodel.Query#getTable <em>Table</em>}</li>
 *   <li>{@link org.omnia.metamodel.metamodel.Query#getJoins <em>Joins</em>}</li>
 * </ul>
 *
 * @see org.omnia.metamodel.metamodel.MetamodelPackage#getQuery()
 * @model
 * @generated
 */
public interface Query extends EObject
{
  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see org.omnia.metamodel.metamodel.MetamodelPackage#getQuery_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link org.omnia.metamodel.metamodel.Query#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

  /**
   * Returns the value of the '<em><b>Description</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Description</em>' attribute.
   * @see #setDescription(String)
   * @see org.omnia.metamodel.metamodel.MetamodelPackage#getQuery_Description()
   * @model
   * @generated
   */
  String getDescription();

  /**
   * Sets the value of the '{@link org.omnia.metamodel.metamodel.Query#getDescription <em>Description</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Description</em>' attribute.
   * @see #getDescription()
   * @generated
   */
  void setDescription(String value);

  /**
   * Returns the value of the '<em><b>Expression</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Expression</em>' attribute.
   * @see #setExpression(String)
   * @see org.omnia.metamodel.metamodel.MetamodelPackage#getQuery_Expression()
   * @model
   * @generated
   */
  String getExpression();

  /**
   * Sets the value of the '{@link org.omnia.metamodel.metamodel.Query#getExpression <em>Expression</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Expression</em>' attribute.
   * @see #getExpression()
   * @generated
   */
  void setExpression(String value);

  /**
   * Returns the value of the '<em><b>Data Source</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Data Source</em>' reference.
   * @see #setDataSource(DataSource)
   * @see org.omnia.metamodel.metamodel.MetamodelPackage#getQuery_DataSource()
   * @model
   * @generated
   */
  DataSource getDataSource();

  /**
   * Sets the value of the '{@link org.omnia.metamodel.metamodel.Query#getDataSource <em>Data Source</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Data Source</em>' reference.
   * @see #getDataSource()
   * @generated
   */
  void setDataSource(DataSource value);

  /**
   * Returns the value of the '<em><b>Table</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Table</em>' containment reference.
   * @see #setTable(QueryTable)
   * @see org.omnia.metamodel.metamodel.MetamodelPackage#getQuery_Table()
   * @model containment="true"
   * @generated
   */
  QueryTable getTable();

  /**
   * Sets the value of the '{@link org.omnia.metamodel.metamodel.Query#getTable <em>Table</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Table</em>' containment reference.
   * @see #getTable()
   * @generated
   */
  void setTable(QueryTable value);

  /**
   * Returns the value of the '<em><b>Joins</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Joins</em>' containment reference.
   * @see #setJoins(QueryJoin)
   * @see org.omnia.metamodel.metamodel.MetamodelPackage#getQuery_Joins()
   * @model containment="true"
   * @generated
   */
  QueryJoin getJoins();

  /**
   * Sets the value of the '{@link org.omnia.metamodel.metamodel.Query#getJoins <em>Joins</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Joins</em>' containment reference.
   * @see #getJoins()
   * @generated
   */
  void setJoins(QueryJoin value);

} // Query
