/**
 * generated by Xtext 2.27.0
 */
package org.omnia.metamodel.metamodel;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>State Enabled Operation</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.omnia.metamodel.metamodel.StateEnabledOperation#getName <em>Name</em>}</li>
 *   <li>{@link org.omnia.metamodel.metamodel.StateEnabledOperation#getDescription <em>Description</em>}</li>
 *   <li>{@link org.omnia.metamodel.metamodel.StateEnabledOperation#getPath <em>Path</em>}</li>
 *   <li>{@link org.omnia.metamodel.metamodel.StateEnabledOperation#getType <em>Type</em>}</li>
 * </ul>
 *
 * @see org.omnia.metamodel.metamodel.MetamodelPackage#getStateEnabledOperation()
 * @model
 * @generated
 */
public interface StateEnabledOperation extends EObject
{
  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see org.omnia.metamodel.metamodel.MetamodelPackage#getStateEnabledOperation_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link org.omnia.metamodel.metamodel.StateEnabledOperation#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

  /**
   * Returns the value of the '<em><b>Description</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Description</em>' attribute.
   * @see #setDescription(String)
   * @see org.omnia.metamodel.metamodel.MetamodelPackage#getStateEnabledOperation_Description()
   * @model
   * @generated
   */
  String getDescription();

  /**
   * Sets the value of the '{@link org.omnia.metamodel.metamodel.StateEnabledOperation#getDescription <em>Description</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Description</em>' attribute.
   * @see #getDescription()
   * @generated
   */
  void setDescription(String value);

  /**
   * Returns the value of the '<em><b>Path</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Path</em>' attribute.
   * @see #setPath(String)
   * @see org.omnia.metamodel.metamodel.MetamodelPackage#getStateEnabledOperation_Path()
   * @model
   * @generated
   */
  String getPath();

  /**
   * Sets the value of the '{@link org.omnia.metamodel.metamodel.StateEnabledOperation#getPath <em>Path</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Path</em>' attribute.
   * @see #getPath()
   * @generated
   */
  void setPath(String value);

  /**
   * Returns the value of the '<em><b>Type</b></em>' attribute.
   * The literals are from the enumeration {@link org.omnia.metamodel.metamodel.StateEnabledOperationTypeEnum}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Type</em>' attribute.
   * @see org.omnia.metamodel.metamodel.StateEnabledOperationTypeEnum
   * @see #setType(StateEnabledOperationTypeEnum)
   * @see org.omnia.metamodel.metamodel.MetamodelPackage#getStateEnabledOperation_Type()
   * @model
   * @generated
   */
  StateEnabledOperationTypeEnum getType();

  /**
   * Sets the value of the '{@link org.omnia.metamodel.metamodel.StateEnabledOperation#getType <em>Type</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Type</em>' attribute.
   * @see org.omnia.metamodel.metamodel.StateEnabledOperationTypeEnum
   * @see #getType()
   * @generated
   */
  void setType(StateEnabledOperationTypeEnum value);

} // StateEnabledOperation
