/**
 * generated by Xtext 2.27.0
 */
package org.omnia.metamodel.metamodel;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>State</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.omnia.metamodel.metamodel.State#isIsInitial <em>Is Initial</em>}</li>
 *   <li>{@link org.omnia.metamodel.metamodel.State#isDisableOperations <em>Disable Operations</em>}</li>
 *   <li>{@link org.omnia.metamodel.metamodel.State#isDisableAttributes <em>Disable Attributes</em>}</li>
 *   <li>{@link org.omnia.metamodel.metamodel.State#getName <em>Name</em>}</li>
 *   <li>{@link org.omnia.metamodel.metamodel.State#getDescription <em>Description</em>}</li>
 *   <li>{@link org.omnia.metamodel.metamodel.State#getAssignToExpression <em>Assign To Expression</em>}</li>
 *   <li>{@link org.omnia.metamodel.metamodel.State#getTransitions <em>Transitions</em>}</li>
 *   <li>{@link org.omnia.metamodel.metamodel.State#getDecisions <em>Decisions</em>}</li>
 *   <li>{@link org.omnia.metamodel.metamodel.State#getEnableOperations <em>Enable Operations</em>}</li>
 *   <li>{@link org.omnia.metamodel.metamodel.State#getEnabledAttributes <em>Enabled Attributes</em>}</li>
 *   <li>{@link org.omnia.metamodel.metamodel.State#getBehaviours <em>Behaviours</em>}</li>
 * </ul>
 *
 * @see org.omnia.metamodel.metamodel.MetamodelPackage#getState()
 * @model
 * @generated
 */
public interface State extends EObject
{
  /**
   * Returns the value of the '<em><b>Is Initial</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Is Initial</em>' attribute.
   * @see #setIsInitial(boolean)
   * @see org.omnia.metamodel.metamodel.MetamodelPackage#getState_IsInitial()
   * @model
   * @generated
   */
  boolean isIsInitial();

  /**
   * Sets the value of the '{@link org.omnia.metamodel.metamodel.State#isIsInitial <em>Is Initial</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Is Initial</em>' attribute.
   * @see #isIsInitial()
   * @generated
   */
  void setIsInitial(boolean value);

  /**
   * Returns the value of the '<em><b>Disable Operations</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Disable Operations</em>' attribute.
   * @see #setDisableOperations(boolean)
   * @see org.omnia.metamodel.metamodel.MetamodelPackage#getState_DisableOperations()
   * @model
   * @generated
   */
  boolean isDisableOperations();

  /**
   * Sets the value of the '{@link org.omnia.metamodel.metamodel.State#isDisableOperations <em>Disable Operations</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Disable Operations</em>' attribute.
   * @see #isDisableOperations()
   * @generated
   */
  void setDisableOperations(boolean value);

  /**
   * Returns the value of the '<em><b>Disable Attributes</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Disable Attributes</em>' attribute.
   * @see #setDisableAttributes(boolean)
   * @see org.omnia.metamodel.metamodel.MetamodelPackage#getState_DisableAttributes()
   * @model
   * @generated
   */
  boolean isDisableAttributes();

  /**
   * Sets the value of the '{@link org.omnia.metamodel.metamodel.State#isDisableAttributes <em>Disable Attributes</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Disable Attributes</em>' attribute.
   * @see #isDisableAttributes()
   * @generated
   */
  void setDisableAttributes(boolean value);

  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see org.omnia.metamodel.metamodel.MetamodelPackage#getState_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link org.omnia.metamodel.metamodel.State#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

  /**
   * Returns the value of the '<em><b>Description</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Description</em>' attribute.
   * @see #setDescription(String)
   * @see org.omnia.metamodel.metamodel.MetamodelPackage#getState_Description()
   * @model
   * @generated
   */
  String getDescription();

  /**
   * Sets the value of the '{@link org.omnia.metamodel.metamodel.State#getDescription <em>Description</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Description</em>' attribute.
   * @see #getDescription()
   * @generated
   */
  void setDescription(String value);

  /**
   * Returns the value of the '<em><b>Assign To Expression</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Assign To Expression</em>' attribute.
   * @see #setAssignToExpression(String)
   * @see org.omnia.metamodel.metamodel.MetamodelPackage#getState_AssignToExpression()
   * @model
   * @generated
   */
  String getAssignToExpression();

  /**
   * Sets the value of the '{@link org.omnia.metamodel.metamodel.State#getAssignToExpression <em>Assign To Expression</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Assign To Expression</em>' attribute.
   * @see #getAssignToExpression()
   * @generated
   */
  void setAssignToExpression(String value);

  /**
   * Returns the value of the '<em><b>Transitions</b></em>' containment reference list.
   * The list contents are of type {@link org.omnia.metamodel.metamodel.StateTransition}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Transitions</em>' containment reference list.
   * @see org.omnia.metamodel.metamodel.MetamodelPackage#getState_Transitions()
   * @model containment="true"
   * @generated
   */
  EList<StateTransition> getTransitions();

  /**
   * Returns the value of the '<em><b>Decisions</b></em>' containment reference list.
   * The list contents are of type {@link org.omnia.metamodel.metamodel.StateDecision}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Decisions</em>' containment reference list.
   * @see org.omnia.metamodel.metamodel.MetamodelPackage#getState_Decisions()
   * @model containment="true"
   * @generated
   */
  EList<StateDecision> getDecisions();

  /**
   * Returns the value of the '<em><b>Enable Operations</b></em>' containment reference list.
   * The list contents are of type {@link org.omnia.metamodel.metamodel.StateEnabledOperation}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Enable Operations</em>' containment reference list.
   * @see org.omnia.metamodel.metamodel.MetamodelPackage#getState_EnableOperations()
   * @model containment="true"
   * @generated
   */
  EList<StateEnabledOperation> getEnableOperations();

  /**
   * Returns the value of the '<em><b>Enabled Attributes</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Enabled Attributes</em>' containment reference.
   * @see #setEnabledAttributes(StateEnabledAttribute)
   * @see org.omnia.metamodel.metamodel.MetamodelPackage#getState_EnabledAttributes()
   * @model containment="true"
   * @generated
   */
  StateEnabledAttribute getEnabledAttributes();

  /**
   * Sets the value of the '{@link org.omnia.metamodel.metamodel.State#getEnabledAttributes <em>Enabled Attributes</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Enabled Attributes</em>' containment reference.
   * @see #getEnabledAttributes()
   * @generated
   */
  void setEnabledAttributes(StateEnabledAttribute value);

  /**
   * Returns the value of the '<em><b>Behaviours</b></em>' containment reference list.
   * The list contents are of type {@link org.omnia.metamodel.metamodel.StateBehaviour}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Behaviours</em>' containment reference list.
   * @see org.omnia.metamodel.metamodel.MetamodelPackage#getState_Behaviours()
   * @model containment="true"
   * @generated
   */
  EList<StateBehaviour> getBehaviours();

} // State
