/*
 * generated by Xtext 2.27.0
 */
package org.eclipse.xtext.example.homeautomation.parser.antlr;

import org.antlr.runtime.Token;
import org.antlr.runtime.TokenSource;
import org.eclipse.xtext.example.homeautomation.parser.antlr.internal.InternalRuleEngineParser;
import org.eclipse.xtext.parser.antlr.AbstractIndentationTokenSource;

public class RuleEngineTokenSource extends AbstractIndentationTokenSource {

	public RuleEngineTokenSource(TokenSource delegate) {
		super(delegate);
	}

	@Override
	protected boolean shouldSplitTokenImpl(Token token) {
		// TODO Review assumption
		return token.getType() == InternalRuleEngineParser.RULE_WS;
	}

	@Override
	protected int getBeginTokenType() {
		// TODO Review assumption
		return InternalRuleEngineParser.RULE_BEGIN;
	}

	@Override
	protected int getEndTokenType() {
		// TODO Review assumption
		return InternalRuleEngineParser.RULE_END;
	}

}
