/*
 * generated by Xtext 2.27.0
 */
package org.eclipse.xtext.example.domainmodel.ide;


/**
 * Use this class to register ide components.
 */
public class DomainmodelIdeModule extends AbstractDomainmodelIdeModule {
}
