/*
 * generated by Xtext 2.27.0
 */
package org.eclipse.xtext.example.arithmetics.ide;


/**
 * Use this class to register ide components.
 */
public class ArithmeticsIdeModule extends AbstractArithmeticsIdeModule {
}
