/*
 * generated by Xtext 2.27.0
 */
package org.omnia.metamodel.parser.antlr;

import com.google.inject.Inject;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import org.omnia.metamodel.parser.antlr.internal.InternalMetamodelParser;
import org.omnia.metamodel.services.MetamodelGrammarAccess;

public class MetamodelParser extends AbstractAntlrParser {

	@Inject
	private MetamodelGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalMetamodelParser createParser(XtextTokenStream stream) {
		return new InternalMetamodelParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "App";
	}

	public MetamodelGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(MetamodelGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
