/*
 * generated by Xtext 2.27.0
 */
package org.eclipse.xtext.example.arithmetics.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractArithmeticsScopeProvider extends DelegatingScopeProvider {
}
