/*
 * generated by Xtext 2.27.0
 */
package org.eclipse.xtext.example.fowlerdsl.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import org.eclipse.xtext.example.fowlerdsl.StatemachineRuntimeModule;
import org.eclipse.xtext.example.fowlerdsl.StatemachineStandaloneSetup;
import org.eclipse.xtext.util.Modules2;

/**
 * Initialization support for running Xtext languages as language servers.
 */
public class StatemachineIdeSetup extends StatemachineStandaloneSetup {

	@Override
	public Injector createInjector() {
		return Guice.createInjector(Modules2.mixin(new StatemachineRuntimeModule(), new StatemachineIdeModule()));
	}
	
}
