/*
 * generated by Xtext 2.27.0
 */
package org.eclipse.xtext.example.homeautomation.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import org.eclipse.xtext.example.homeautomation.RuleEngineRuntimeModule;
import org.eclipse.xtext.example.homeautomation.RuleEngineStandaloneSetup;
import org.eclipse.xtext.util.Modules2;

/**
 * Initialization support for running Xtext languages as language servers.
 */
public class RuleEngineIdeSetup extends RuleEngineStandaloneSetup {

	@Override
	public Injector createInjector() {
		return Guice.createInjector(Modules2.mixin(new RuleEngineRuntimeModule(), new RuleEngineIdeModule()));
	}
	
}
