/*
 * generated by Xtext 2.27.0
 */
package org.eclipse.xtext.example.arithmetics;


/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class ArithmeticsRuntimeModule extends AbstractArithmeticsRuntimeModule {
}
